/**
 * Shared platform registry for username-based profile checking.
 * Used by both namechk.js and socialProfiles.js to avoid duplicate lists.
 */
const PLATFORMS = [

  // ── Code & Dev ──────────────────────────────────────────────────────
  { id: 'GitHub', url: u => `https://github.com/${u}` },
  { id: 'Gist', url: u => `https://gist.github.com/${u}` },
  { id: 'GitLab', url: u => `https://gitlab.com/${u}` },
  { id: 'Bitbucket', url: u => `https://bitbucket.org/${u}` },
  { id: 'SourceHut', url: u => `https://sr.ht/~${u}` },
  { id: 'Codeberg', url: u => `https://codeberg.org/${u}` },
  { id: 'Gitea', url: u => `https://gitea.com/${u}` },
  { id: 'Gitee', url: u => `https://gitee.com/${u}` },
  { id: 'Docker Hub', url: u => `https://hub.docker.com/u/${u}` },
  { id: 'npm', url: u => `https://www.npmjs.com/~${u}` },
  { id: 'PyPI', url: u => `https://pypi.org/user/${u}` },
  { id: 'RubyGems', url: u => `https://rubygems.org/profiles/${u}` },
  { id: 'Packagist', url: u => `https://packagist.org/users/${u}` },
  { id: 'crates.io', url: u => `https://crates.io/users/${u}` },
  { id: 'Hex.pm', url: u => `https://hex.pm/users/${u}` },
  { id: 'Pub.dev', url: u => `https://pub.dev/publishers/${u}` },
  { id: 'OpenHub', url: u => `https://openhub.net/accounts/${u}` },
  { id: 'CodePen', url: u => `https://codepen.io/${u}` },
  { id: 'Replit', url: u => `https://replit.com/@${u}` },
  { id: 'CodeSandbox', url: u => `https://codesandbox.io/u/${u}` },
  { id: 'Glitch', url: u => `https://glitch.com/@${u}` },
  { id: 'Observable', url: u => `https://observablehq.com/@${u}` },
  { id: 'JSFiddle', url: u => `https://jsfiddle.net/user/${u}` },
  { id: 'Hugging Face', url: u => `https://huggingface.co/${u}` },
  { id: 'Kaggle', url: u => `https://www.kaggle.com/${u}` },
  { id: 'DEV.to', url: u => `https://dev.to/${u}` },
  { id: 'Hashnode', url: u => `https://hashnode.com/@${u}` },
  { id: 'LeetCode', url: u => `https://leetcode.com/${u}` },
  { id: 'HackerRank', url: u => `https://www.hackerrank.com/${u}` },
  { id: 'Codeforces', url: u => `https://codeforces.com/profile/${u}` },
  { id: 'TopCoder', url: u => `https://www.topcoder.com/members/${u}` },
  { id: 'Codewars', url: u => `https://www.codewars.com/users/${u}` },
  { id: 'AtCoder', url: u => `https://atcoder.jp/users/${u}` },
  { id: 'SPOJ', url: u => `https://www.spoj.com/users/${u}` },
  { id: 'Exercism', url: u => `https://exercism.org/profiles/${u}` },

  // ── Social & Networking ─────────────────────────────────────────────
  { id: 'Reddit', url: u => `https://www.reddit.com/user/${u}` },
  { id: 'Medium', url: u => `https://medium.com/@${u}` },
  { id: 'Substack', url: u => `https://substack.com/@${u}` },
  { id: 'Mastodon', url: u => `https://mastodon.social/@${u}` },
  { id: 'Bluesky', url: u => `https://bsky.app/profile/${u}` },
  { id: 'Twitter/X', url: u => `https://x.com/${u}` },
  { id: 'Instagram', url: u => `https://www.instagram.com/${u}/` },
  { id: 'TikTok', url: u => `https://www.tiktok.com/@${u}` },
  { id: 'LinkedIn', url: u => `https://www.linkedin.com/in/${u}` },
  { id: 'Facebook', url: u => `https://www.facebook.com/${u}` },
  { id: 'Snapchat', url: u => `https://www.snapchat.com/add/${u}` },
  { id: 'Threads', url: u => `https://www.threads.net/@${u}` },
  { id: 'Telegram', url: u => `https://t.me/${u}` },
  { id: 'Discord', url: u => `https://discord.com/users/${u}` },
  { id: 'Quora', url: u => `https://www.quora.com/profile/${u}` },
  { id: 'VK', url: u => `https://vk.com/${u}` },
  { id: 'OK.ru', url: u => `https://ok.ru/profile/${u}` },
  { id: 'Clubhouse', url: u => `https://www.clubhouse.com/@${u}` },
  { id: 'Minds', url: u => `https://www.minds.com/${u}` },
  { id: 'Gab', url: u => `https://gab.com/${u}` },
  { id: 'Parler', url: u => `https://parler.com/profile/${u}` },
  { id: 'Plurk', url: u => `https://www.plurk.com/${u}` },
  { id: 'Micro.blog', url: u => `https://micro.blog/${u}` },
  { id: 'Pixelfed', url: u => `https://pixelfed.social/${u}` },
  { id: 'Lemmy', url: u => `https://lemmy.ml/u/${u}` },
  { id: 'Cohost', url: u => `https://cohost.org/${u}` },
  { id: 'Spoutible', url: u => `https://spoutible.com/${u}` },
  { id: 'MeWe', url: u => `https://mewe.com/i/${u}` },
  { id: 'WT.Social', url: u => `https://wt.social/u/${u}` },
  { id: 'Ello', url: u => `https://ello.co/${u}` },
  { id: 'Fosstodon', url: u => `https://fosstodon.org/@${u}` },
  { id: 'Hachyderm', url: u => `https://hachyderm.io/@${u}` },
  { id: 'InfoSec Exchange', url: u => `https://infosec.exchange/@${u}` },
  { id: 'Mstdn.social', url: u => `https://mstdn.social/@${u}` },
  { id: 'Universeodon', url: u => `https://universeodon.com/@${u}` },
  { id: 'Vivaldi Social', url: u => `https://social.vivaldi.net/@${u}` },
  { id: 'TechHub Social', url: u => `https://techhub.social/@${u}` },
  { id: 'XING', url: u => `https://www.xing.com/profile/${u}` },
  { id: 'Rumble User', url: u => `https://rumble.com/user/${u}` },
  { id: 'Koo', url: u => `https://www.kooapp.com/profile/${u}` },
  { id: 'Hive Social', url: u => `https://www.hivesocial.app/${u}` },
  { id: 'Lemon8', url: u => `https://www.lemon8-app.com/${u}` },
  { id: 'BeReal', url: u => `https://bfrnd.link/${u}` },
  { id: 'Gettr', url: u => `https://gettr.com/user/${u}` },
  { id: 'Counter.Social', url: u => `https://counter.social/@${u}` },

  // ── Video & Streaming ──────────────────────────────────────────────
  { id: 'YouTube', url: u => `https://www.youtube.com/@${u}` },
  { id: 'Twitch', url: u => `https://www.twitch.tv/${u}` },
  { id: 'Vimeo', url: u => `https://vimeo.com/${u}` },
  { id: 'Dailymotion', url: u => `https://www.dailymotion.com/${u}` },
  { id: 'Rumble', url: u => `https://rumble.com/c/${u}` },
  { id: 'Odysee', url: u => `https://odysee.com/@${u}` },
  { id: 'BitChute', url: u => `https://www.bitchute.com/channel/${u}` },
  { id: 'Kick', url: u => `https://kick.com/${u}` },
  { id: 'Mixcloud', url: u => `https://www.mixcloud.com/${u}` },
  { id: 'PeerTube', url: u => `https://peertube.tv/accounts/${u}` },
  { id: 'Newgrounds', url: u => `https://${u}.newgrounds.com` },
  { id: 'Vidlii', url: u => `https://www.vidlii.com/user/${u}` },
  { id: 'Veoh', url: u => `https://www.veoh.com/users/${u}` },
  { id: 'Niconico', url: u => `https://www.nicovideo.jp/user/${u}` },
  { id: 'Vlare', url: u => `https://vlare.tv/c/${u}` },
  { id: 'Streamable', url: u => `https://streamable.com/${u}` },
  { id: 'Trovo', url: u => `https://trovo.live/${u}` },
  { id: 'Caffeine', url: u => `https://www.caffeine.tv/${u}` },

  // ── Audio & Music ──────────────────────────────────────────────────
  { id: 'SoundCloud', url: u => `https://soundcloud.com/${u}` },
  { id: 'Bandcamp', url: u => `https://${u}.bandcamp.com` },
  { id: 'Spotify', url: u => `https://open.spotify.com/user/${u}` },
  { id: 'Last.fm', url: u => `https://www.last.fm/user/${u}` },
  { id: 'Audiomack', url: u => `https://audiomack.com/${u}` },
  { id: 'ReverbNation', url: u => `https://www.reverbnation.com/${u}` },
  { id: 'Mixlr', url: u => `https://mixlr.com/${u}` },
  { id: 'Spreaker', url: u => `https://www.spreaker.com/user/${u}` },
  { id: 'Podbean', url: u => `https://${u}.podbean.com` },
  { id: 'Genius', url: u => `https://genius.com/artists/${u}` },
  { id: 'Discogs', url: u => `https://www.discogs.com/user/${u}` },
  { id: 'Rate Your Music', url: u => `https://rateyourmusic.com/~${u}` },
  { id: 'Musescore', url: u => `https://musescore.com/user/${u}` },
  { id: 'BandLab', url: u => `https://www.bandlab.com/${u}` },
  { id: 'Deezer', url: u => `https://www.deezer.com/profile/${u}` },
  { id: 'Anghami', url: u => `https://play.anghami.com/artist/${u}` },
  { id: 'TIDAL', url: u => `https://listen.tidal.com/artist/${u}` },
  { id: 'Resso', url: u => `https://www.resso.com/user/${u}` },
  { id: 'Apple Podcasts', url: u => `https://podcasters.apple.com/${u}` },
  { id: 'Podomatic', url: u => `https://www.podomatic.com/podcasts/${u}` },

  // ── Images / Design / Art ──────────────────────────────────────────
  { id: 'Flickr', url: u => `https://www.flickr.com/photos/${u}/` },
  { id: 'Imgur', url: u => `https://imgur.com/user/${u}` },
  { id: 'Pinterest', url: u => `https://www.pinterest.com/${u}/` },
  { id: 'Behance', url: u => `https://www.behance.net/${u}` },
  { id: 'Dribbble', url: u => `https://dribbble.com/${u}` },
  { id: 'DeviantArt', url: u => `https://www.deviantart.com/${u}` },
  { id: '500px', url: u => `https://500px.com/p/${u}` },
  { id: 'Unsplash', url: u => `https://unsplash.com/@${u}` },
  { id: 'VSCO', url: u => `https://vsco.co/${u}/gallery` },
  { id: 'ArtStation', url: u => `https://www.artstation.com/${u}` },
  { id: 'SmugMug', url: u => `https://${u}.smugmug.com` },
  { id: 'Giphy', url: u => `https://giphy.com/${u}` },
  { id: 'Pexels', url: u => `https://www.pexels.com/@${u}` },
  { id: 'Coroflot', url: u => `https://www.coroflot.com/${u}` },
  { id: 'Ello Art', url: u => `https://ello.co/${u}` },
  { id: 'Artfol', url: u => `https://artfol.co/${u}` },
  { id: 'Cara', url: u => `https://cara.app/${u}` },
  { id: 'CGSociety', url: u => `https://www.cgsociety.org/${u}` },
  { id: 'Pixiv', url: u => `https://www.pixiv.net/users/${u}` },
  { id: 'Sketchfab', url: u => `https://sketchfab.com/${u}` },
  { id: 'Lottiefiles', url: u => `https://lottiefiles.com/${u}` },
  { id: 'Figma', url: u => `https://www.figma.com/@${u}` },
  { id: 'Canva', url: u => `https://www.canva.com/p/${u}` },
  { id: 'Redbubble', url: u => `https://www.redbubble.com/people/${u}` },
  { id: 'Society6', url: u => `https://society6.com/${u}` },

  // ── Photography ────────────────────────────────────────────────────
  { id: 'EyeEm', url: u => `https://www.eyeem.com/u/${u}` },
  { id: 'ViewBug', url: u => `https://www.viewbug.com/member/${u}` },
  { id: 'Photobucket', url: u => `https://photobucket.com/user/${u}` },
  { id: 'GuruShots', url: u => `https://gurushots.com/${u}/photos` },
  { id: 'YourShot', url: u => `https://yourshot.nationalgeographic.com/profile/${u}` },

  // ── Blogging & Publishing ──────────────────────────────────────────
  { id: 'Tumblr', url: u => `https://${u}.tumblr.com` },
  { id: 'WordPress', url: u => `https://${u}.wordpress.com` },
  { id: 'Blogger', url: u => `https://${u}.blogspot.com` },
  { id: 'Ghost', url: u => `https://${u}.ghost.io` },
  { id: 'Wix', url: u => `https://${u}.wixsite.com` },
  { id: 'Write.as', url: u => `https://write.as/${u}` },
  { id: 'Telegraph', url: u => `https://telegra.ph/${u}` },
  { id: 'Typefully', url: u => `https://typefully.com/${u}` },
  { id: 'Bear Blog', url: u => `https://${u}.bearblog.dev` },
  { id: 'Svbtle', url: u => `https://${u}.svbtle.com` },
  { id: 'Posthaven', url: u => `https://${u}.posthaven.com` },
  { id: 'Prose.io', url: u => `https://prose.io/#${u}` },
  { id: 'Silvrback', url: u => `https://${u}.silvrback.com` },
  { id: 'HubPages', url: u => `https://hubpages.com/@${u}` },
  { id: 'Penzu', url: u => `https://penzu.com/public/${u}` },

  // ── Gaming ─────────────────────────────────────────────────────────
  { id: 'Steam', url: u => `https://steamcommunity.com/id/${u}` },
  { id: 'itch.io', url: u => `https://${u}.itch.io` },
  { id: 'Game Jolt', url: u => `https://gamejolt.com/@${u}` },
  { id: 'Newgrounds Gaming', url: u => `https://${u}.newgrounds.com/games` },
  { id: 'Chess.com', url: u => `https://www.chess.com/member/${u}` },
  { id: 'Lichess', url: u => `https://lichess.org/@/${u}` },
  { id: 'osu!', url: u => `https://osu.ppy.sh/users/${u}` },
  { id: 'Speedrun.com', url: u => `https://www.speedrun.com/users/${u}` },
  { id: 'RetroAchievements', url: u => `https://retroachievements.org/user/${u}` },
  { id: 'NameMC', url: u => `https://namemc.com/profile/${u}` },
  { id: 'Roblox', url: u => `https://www.roblox.com/user.aspx?username=${u}` },
  { id: 'Fortnite Tracker', url: u => `https://fortnitetracker.com/profile/all/${u}` },
  { id: 'Valorant Tracker', url: u => `https://tracker.gg/valorant/profile/riot/${u}` },
  { id: 'OP.GG', url: u => `https://www.op.gg/summoners/na/${u}` },
  { id: 'Mobalytics', url: u => `https://mobalytics.gg/lol/profile/na/${u}` },
  { id: 'Tracker.gg', url: u => `https://tracker.gg/profile/${u}` },
  { id: 'Xbox Gamertag', url: u => `https://www.xbox.com/en-US/play/user/${u}` },
  { id: 'PSN Profiles', url: u => `https://psnprofiles.com/${u}` },
  { id: 'Nintendo', url: u => `https://nintendo.com/profile/${u}` },
  { id: 'Torn', url: u => `https://www.torn.com/profiles.php?XID=${u}` },
  { id: 'Backloggd', url: u => `https://www.backloggd.com/u/${u}` },
  { id: 'GG.deals', url: u => `https://gg.deals/user/${u}` },
  { id: 'IGDB', url: u => `https://www.igdb.com/users/${u}` },
  { id: 'Lutris', url: u => `https://lutris.net/users/${u}` },
  { id: 'PlayTracker', url: u => `https://playtracker.net/user/${u}` },
  { id: 'GOG', url: u => `https://www.gog.com/u/${u}` },
  { id: 'Epic Games', url: u => `https://store.epicgames.com/u/${u}` },
  { id: 'GameFAQs', url: u => `https://gamefaqs.gamespot.com/community/${u}` },
  { id: 'Giant Bomb', url: u => `https://www.giantbomb.com/profile/${u}` },
  { id: 'NexusMods', url: u => `https://www.nexusmods.com/users/${u}` },

  // ── Shopping & Marketplace ─────────────────────────────────────────
  { id: 'eBay', url: u => `https://www.ebay.com/usr/${u}` },
  { id: 'Etsy', url: u => `https://www.etsy.com/shop/${u}` },
  { id: 'Poshmark', url: u => `https://poshmark.com/closet/${u}` },
  { id: 'Depop', url: u => `https://www.depop.com/${u}` },
  { id: 'Storenvy', url: u => `https://${u}.storenvy.com` },
  { id: 'Redbubble Shop', url: u => `https://www.redbubble.com/people/${u}/shop` },
  { id: 'Zazzle', url: u => `https://www.zazzle.com/store/${u}` },
  { id: 'Teespring', url: u => `https://teespring.com/stores/${u}` },
  { id: 'Mercari', url: u => `https://www.mercari.com/u/${u}` },
  { id: 'Vinted', url: u => `https://www.vinted.com/member/${u}` },
  { id: 'Grailed', url: u => `https://www.grailed.com/${u}` },
  { id: 'StockX', url: u => `https://stockx.com/${u}` },
  { id: 'Reverb', url: u => `https://reverb.com/shop/${u}` },
  { id: 'Discogs Market', url: u => `https://www.discogs.com/seller/${u}` },
  { id: 'Swappa', url: u => `https://swappa.com/user/${u}` },

  // ── Business & Professional ────────────────────────────────────────
  { id: 'AngelList', url: u => `https://angel.co/u/${u}` },
  { id: 'Crunchbase', url: u => `https://www.crunchbase.com/person/${u}` },
  { id: 'Product Hunt', url: u => `https://www.producthunt.com/@${u}` },
  { id: 'Indie Hackers', url: u => `https://www.indiehackers.com/${u}` },
  { id: 'Fiverr', url: u => `https://www.fiverr.com/${u}` },
  { id: 'Freelancer', url: u => `https://www.freelancer.com/u/${u}` },
  { id: 'Toptal', url: u => `https://www.toptal.com/resume/${u}` },
  { id: 'Wellfound', url: u => `https://wellfound.com/u/${u}` },
  { id: 'F6S', url: u => `https://www.f6s.com/${u}` },
  { id: 'Polywork', url: u => `https://www.polywork.com/${u}` },
  { id: 'Peerlist', url: u => `https://peerlist.io/${u}` },
  { id: 'Read.cv', url: u => `https://read.cv/${u}` },
  { id: 'Contra', url: u => `https://contra.com/${u}` },
  { id: 'Glassdoor', url: u => `https://www.glassdoor.com/member/profile/${u}` },
  { id: 'Guru', url: u => `https://www.guru.com/freelancers/${u}` },
  { id: 'PeoplePerHour', url: u => `https://www.peopleperhour.com/freelancer/${u}` },
  { id: '99designs', url: u => `https://99designs.com/profiles/${u}` },
  { id: 'DesignCrowd', url: u => `https://www.designcrowd.com/designer/${u}` },
  { id: 'Clarity.fm', url: u => `https://clarity.fm/${u}` },
  { id: 'Calendly', url: u => `https://calendly.com/${u}` },

  // ── Finance & Crypto ───────────────────────────────────────────────
  { id: 'TradingView', url: u => `https://www.tradingview.com/u/${u}` },
  { id: 'OpenSea', url: u => `https://opensea.io/${u}` },
  { id: 'Rarible', url: u => `https://rarible.com/${u}` },
  { id: 'Foundation', url: u => `https://foundation.app/@${u}` },
  { id: 'Mirror', url: u => `https://mirror.xyz/${u}` },
  { id: 'CoinGecko', url: u => `https://www.coingecko.com/en/accounts/${u}` },
  { id: 'Polymarket', url: u => `https://polymarket.com/profile/${u}` },
  { id: 'Zapper', url: u => `https://zapper.xyz/account/${u}` },
  { id: 'DeBank', url: u => `https://debank.com/profile/${u}` },
  { id: 'Etherscan', url: u => `https://etherscan.io/address/${u}` },
  { id: 'CoinMarketCap', url: u => `https://coinmarketcap.com/community/profile/${u}` },
  { id: 'Binance', url: u => `https://www.binance.com/en/feed/profile/${u}` },

  // ── Science & Academic ─────────────────────────────────────────────
  { id: 'ResearchGate', url: u => `https://www.researchgate.net/profile/${u}` },
  { id: 'Academia.edu', url: u => `https://independent.academia.edu/${u}` },
  { id: 'ORCID', url: u => `https://orcid.org/${u}` },
  { id: 'Google Scholar', url: u => `https://scholar.google.com/citations?user=${u}` },
  { id: 'Semantic Scholar', url: u => `https://www.semanticscholar.org/author/${u}` },
  { id: 'Publons', url: u => `https://publons.com/researcher/${u}` },
  { id: 'Scopus', url: u => `https://www.scopus.com/authid/detail.uri?authorId=${u}` },
  { id: 'Loop', url: u => `https://loop.frontiersin.org/people/${u}` },
  { id: 'Mendeley', url: u => `https://www.mendeley.com/profiles/${u}` },
  { id: 'Zenodo', url: u => `https://zenodo.org/search?q=${u}` },
  { id: 'Figshare', url: u => `https://figshare.com/authors/${u}` },
  { id: 'bioRxiv', url: u => `https://www.biorxiv.org/search/author1:${u}` },
  { id: 'arXiv Author', url: u => `https://arxiv.org/search/?searchtype=author&query=${u}` },
  { id: 'DBLP', url: u => `https://dblp.org/pid/${u}` },
  { id: 'IEEE Xplore', url: u => `https://ieeexplore.ieee.org/author/${u}` },

  // ── Education & Learning ───────────────────────────────────────────
  { id: 'Khan Academy', url: u => `https://www.khanacademy.org/profile/${u}` },
  { id: 'Udemy', url: u => `https://www.udemy.com/user/${u}` },
  { id: 'Duolingo', url: u => `https://www.duolingo.com/profile/${u}` },
  { id: 'Memrise', url: u => `https://www.memrise.com/user/${u}` },
  { id: 'Quizlet', url: u => `https://quizlet.com/${u}` },
  { id: 'Instructables', url: u => `https://www.instructables.com/member/${u}` },
  { id: 'Skillshare', url: u => `https://www.skillshare.com/profile/${u}` },
  { id: 'Codecademy', url: u => `https://www.codecademy.com/profiles/${u}` },
  { id: 'Brilliant', url: u => `https://brilliant.org/profile/${u}` },
  { id: 'Coursera', url: u => `https://www.coursera.org/user/${u}` },
  { id: 'edX', url: u => `https://profile.edx.org/u/${u}` },
  { id: 'Pluralsight', url: u => `https://app.pluralsight.com/profile/${u}` },

  // ── Books & Reading ────────────────────────────────────────────────
  { id: 'Goodreads', url: u => `https://www.goodreads.com/${u}` },
  { id: 'LibraryThing', url: u => `https://www.librarything.com/profile/${u}` },
  { id: 'BookBub', url: u => `https://www.bookbub.com/profile/${u}` },
  { id: 'StoryGraph', url: u => `https://app.thestorygraph.com/profile/${u}` },
  { id: 'Wattpad', url: u => `https://www.wattpad.com/user/${u}` },
  { id: 'Archive of Our Own', url: u => `https://archiveofourown.org/users/${u}` },
  { id: 'Royal Road', url: u => `https://www.royalroad.com/profile/${u}` },
  { id: 'Smashwords', url: u => `https://www.smashwords.com/profile/view/${u}` },
  { id: 'Lulu', url: u => `https://www.lulu.com/spotlight/${u}` },
  { id: 'Draft2Digital', url: u => `https://www.draft2digital.com/author/${u}` },

  // ── Film / TV / Anime ──────────────────────────────────────────────
  { id: 'Letterboxd', url: u => `https://letterboxd.com/${u}` },
  { id: 'Trakt', url: u => `https://trakt.tv/users/${u}` },
  { id: 'MyAnimeList', url: u => `https://myanimelist.net/profile/${u}` },
  { id: 'AniList', url: u => `https://anilist.co/user/${u}` },
  { id: 'Kitsu', url: u => `https://kitsu.app/users/${u}` },
  { id: 'IMDb', url: u => `https://www.imdb.com/user/${u}` },
  { id: 'TMDb', url: u => `https://www.themoviedb.org/u/${u}` },
  { id: 'Simkl', url: u => `https://simkl.com/${u}` },
  { id: 'TV Time', url: u => `https://www.tvtime.com/user/${u}` },
  { id: 'Serializd', url: u => `https://www.serializd.com/user/${u}` },
  { id: 'JustWatch', url: u => `https://www.justwatch.com/profile/${u}` },
  { id: 'Filmow', url: u => `https://filmow.com/usuario/${u}` },
  { id: 'Criticker', url: u => `https://www.criticker.com/profile/${u}` },
  { id: 'ICheckMovies', url: u => `https://www.icheckmovies.com/profiles/${u}` },
  { id: 'Cinemagoer', url: u => `https://www.cinemagoer.com/user/${u}` },

  // ── Travel & Outdoors ──────────────────────────────────────────────
  { id: 'TripAdvisor', url: u => `https://www.tripadvisor.com/Profile/${u}` },
  { id: 'Foursquare', url: u => `https://foursquare.com/user/${u}` },
  { id: 'Couchsurfing', url: u => `https://www.couchsurfing.com/people/${u}` },
  { id: 'Polarsteps', url: u => `https://www.polarsteps.com/${u}` },
  { id: 'AllTrails', url: u => `https://www.alltrails.com/members/${u}` },
  { id: 'iNaturalist', url: u => `https://www.inaturalist.org/people/${u}` },
  { id: 'eBird', url: u => `https://ebird.org/profile/${u}` },
  { id: 'Geocaching', url: u => `https://www.geocaching.com/p/default.aspx?u=${u}` },
  { id: 'Komoot', url: u => `https://www.komoot.com/user/${u}` },
  { id: 'Wikiloc', url: u => `https://www.wikiloc.com/wikiloc/user.do?id=${u}` },

  // ── Food & Drink ───────────────────────────────────────────────────
  { id: 'Untappd', url: u => `https://untappd.com/user/${u}` },
  { id: 'Vivino', url: u => `https://www.vivino.com/users/${u}` },
  { id: 'Allrecipes', url: u => `https://www.allrecipes.com/cook/${u}` },
  { id: 'Cookpad', url: u => `https://cookpad.com/us/users/${u}` },
  { id: 'Food52', url: u => `https://food52.com/users/${u}` },
  { id: 'Yummly', url: u => `https://www.yummly.com/profile/${u}` },
  { id: 'Forks Over Knives', url: u => `https://www.forksoverknives.com/profiles/${u}` },
  { id: 'HappyCow', url: u => `https://www.happycow.net/members/profile/${u}` },

  // ── Sports & Fitness ───────────────────────────────────────────────
  { id: 'Strava', url: u => `https://www.strava.com/athletes/${u}` },
  { id: 'MyFitnessPal', url: u => `https://www.myfitnesspal.com/profile/${u}` },
  { id: 'MapMyRun', url: u => `https://www.mapmyrun.com/profile/${u}` },
  { id: 'Fitocracy', url: u => `https://www.fitocracy.com/profile/${u}` },
  { id: 'Garmin Connect', url: u => `https://connect.garmin.com/modern/profile/${u}` },
  { id: 'Peloton', url: u => `https://members.onepeloton.com/members/${u}` },
  { id: 'Nike Run Club', url: u => `https://www.nike.com/member/profile/${u}` },
  { id: 'Athlinks', url: u => `https://www.athlinks.com/athletes/${u}` },
  { id: 'SportTracks', url: u => `https://sporttracks.mobi/profile/${u}` },
  { id: 'Smashrun', url: u => `https://smashrun.com/${u}` },

  // ── 3D Printing & Making ───────────────────────────────────────────
  { id: 'Thingiverse', url: u => `https://www.thingiverse.com/${u}` },
  { id: 'MyMiniFactory', url: u => `https://www.myminifactory.com/users/${u}` },
  { id: 'Printables', url: u => `https://www.printables.com/@${u}` },
  { id: 'Cults3D', url: u => `https://cults3d.com/en/users/${u}` },
  { id: 'Thangs', url: u => `https://thangs.com/${u}` },
  { id: 'Hackaday', url: u => `https://hackaday.io/${u}` },
  { id: 'Adafruit', url: u => `https://learn.adafruit.com/users/${u}` },
  { id: 'GrabCAD', url: u => `https://grabcad.com/library?author=${u}` },
  { id: 'TurboSquid', url: u => `https://www.turbosquid.com/Search/Artists/${u}` },
  { id: 'Sketchfab 3D', url: u => `https://sketchfab.com/${u}/models` },

  // ── Crowdfunding & Support ─────────────────────────────────────────
  { id: 'Patreon', url: u => `https://www.patreon.com/${u}` },
  { id: 'Ko-fi', url: u => `https://ko-fi.com/${u}` },
  { id: 'Buy Me a Coffee', url: u => `https://www.buymeacoffee.com/${u}` },
  { id: 'Open Collective', url: u => `https://opencollective.com/${u}` },
  { id: 'Liberapay', url: u => `https://liberapay.com/${u}` },
  { id: 'Gumroad', url: u => `https://gumroad.com/${u}` },
  { id: 'PayPal.me', url: u => `https://paypal.me/${u}` },
  { id: 'Cash App', url: u => `https://cash.app/$${u}` },
  { id: 'Throne', url: u => `https://throne.com/${u}` },
  { id: 'GoFundMe', url: u => `https://www.gofundme.com/f/${u}` },
  { id: 'Kickstarter', url: u => `https://www.kickstarter.com/profile/${u}` },
  { id: 'Indiegogo', url: u => `https://www.indiegogo.com/individuals/${u}` },

  // ── Link-in-Bio & Portfolio ────────────────────────────────────────
  { id: 'Linktree', url: u => `https://linktr.ee/${u}` },
  { id: 'About.me', url: u => `https://about.me/${u}` },
  { id: 'Bento', url: u => `https://bento.me/${u}` },
  { id: 'Bio.link', url: u => `https://bio.link/${u}` },
  { id: 'AllMyLinks', url: u => `https://allmylinks.com/${u}` },
  { id: 'Taplink', url: u => `https://taplink.cc/${u}` },
  { id: 'Carrd', url: u => `https://${u}.carrd.co` },
  { id: 'Campsite', url: u => `https://campsite.bio/${u}` },
  { id: 'Beacons', url: u => `https://beacons.ai/${u}` },
  { id: 'Stan Store', url: u => `https://stan.store/${u}` },
  { id: 'Flowpage', url: u => `https://www.flowpage.com/${u}` },
  { id: 'Milkshake', url: u => `https://msha.ke/${u}` },
  { id: 'Snipfeed', url: u => `https://snipfeed.co/${u}` },
  { id: 'Koji', url: u => `https://withkoji.com/@${u}` },
  { id: 'Later Link', url: u => `https://linkin.bio/${u}` },

  // ── Forums & Communities ───────────────────────────────────────────
  { id: 'Disqus', url: u => `https://disqus.com/by/${u}` },
  { id: 'Hacker News', url: u => `https://news.ycombinator.com/user?id=${u}` },
  { id: 'Stack Overflow', url: u => `https://stackoverflow.com/users/${u}` },
  { id: 'Wikipedia', url: u => `https://en.wikipedia.org/wiki/User:${u}` },
  { id: 'Fandom', url: u => `https://community.fandom.com/wiki/User:${u}` },
  { id: 'OpenStreetMap', url: u => `https://www.openstreetmap.org/user/${u}` },
  { id: 'Keybase', url: u => `https://keybase.io/${u}` },
  { id: 'Gravatar', url: u => `https://gravatar.com/${u}` },
  { id: 'Lobsters', url: u => `https://lobste.rs/~${u}` },
  { id: 'Slashdot', url: u => `https://slashdot.org/~${u}` },
  { id: 'Something Awful', url: u => `https://forums.somethingawful.com/member.php?action=getinfo&username=${u}` },
  { id: 'NeoGAF', url: u => `https://www.neogaf.com/members/${u}` },
  { id: 'ResetEra', url: u => `https://www.resetera.com/members/${u}` },
  { id: 'GameFAQs Forum', url: u => `https://gamefaqs.gamespot.com/community/${u}/boards` },
  { id: 'XDA Developers', url: u => `https://xdaforums.com/m/${u}` },

  // ── Misc / Utilities ───────────────────────────────────────────────
  { id: 'Pastebin', url: u => `https://pastebin.com/u/${u}` },
  { id: 'SpeakerDeck', url: u => `https://speakerdeck.com/${u}` },
  { id: 'SlideShare', url: u => `https://www.slideshare.net/${u}` },
  { id: 'Issuu', url: u => `https://issuu.com/${u}` },
  { id: 'HackerOne', url: u => `https://hackerone.com/${u}` },
  { id: 'TryHackMe', url: u => `https://tryhackme.com/p/${u}` },
  { id: 'BugCrowd', url: u => `https://bugcrowd.com/${u}` },
  { id: 'IFTTT', url: u => `https://ifttt.com/p/${u}` },
  { id: 'Zapier', url: u => `https://zapier.com/experts/${u}` },
  { id: 'Notion', url: u => `https://${u}.notion.site` },
  { id: 'Airtable', url: u => `https://airtable.com/${u}` },
  { id: 'Trello', url: u => `https://trello.com/${u}` },
  { id: 'Asana', url: u => `https://app.asana.com/u/${u}` },
  { id: 'Miro', url: u => `https://miro.com/app/profile/${u}` },
  { id: 'Loom', url: u => `https://www.loom.com/share/user/${u}` },
  { id: 'Calendly Meeting', url: u => `https://calendly.com/${u}/meeting` },
  { id: 'Doodle', url: u => `https://doodle.com/profile/${u}` },
  { id: 'Bitly', url: u => `https://bitly.com/${u}` },
  { id: 'Rebrandly', url: u => `https://rebrandly.com/${u}` },
  { id: 'Short.io', url: u => `https://short.io/${u}` },

  // ── Mapping & Geo ──────────────────────────────────────────────────
  { id: 'Google Maps Contrib', url: u => `https://www.google.com/maps/contrib/${u}` },
  { id: 'Mapillary', url: u => `https://www.mapillary.com/app/user/${u}` },
  { id: 'OpenStreetMap User', url: u => `https://www.openstreetmap.org/user/${u}/traces` },
  { id: 'HERE WeGo', url: u => `https://wego.here.com/user/${u}` },
  { id: 'Waze', url: u => `https://www.waze.com/user/editor/${u}` },

  // ── Additional Platforms ───────────────────────────────────────────
  { id: 'Wakelet', url: u => `https://wakelet.com/@${u}` },
  { id: 'Flipboard', url: u => `https://flipboard.com/@${u}` },
  { id: 'Pocket', url: u => `https://getpocket.com/@${u}` },
];

export { PLATFORMS };
