export const KEY_DEFS = [
  { id: 'brave', label: 'BRAVE KEY' },
  { id: 'kagi', label: 'KAGI KEY' },
  { id: 'bing', label: 'BING KEY' },
  { id: 'google', label: 'GOOGLE KEY' },
  { id: 'googleCx', label: 'GOOGLE CX' },
  { id: 'serpapi', label: 'SERPAPI KEY' },
  { id: 'mojeek', label: 'MOJEEK KEY' },
  { id: 'exa', label: 'EXA KEY' },
  { id: 'perplexity', label: 'PERPLEXITY KEY' },
  { id: 'shodan', label: 'SHODAN KEY' },
  { id: 'censysId', label: 'CENSYS ID' },
  { id: 'censysSecret', label: 'CENSYS SECRET' },
  { id: 'hunter', label: 'HUNTER KEY' },
  { id: 'intelx', label: 'INTELX KEY' },
  { id: 'publicwww', label: 'PUBLICWWW KEY' },
  { id: 'tineye', label: 'TINEYE KEY' },
  { id: 'dehashed', label: 'DEHASHED email:key' },
  { id: 'hibp', label: 'HIBP API KEY' },
  { id: 'greynoise', label: 'GREYNOISE KEY' },
  { id: 'yandex', label: 'YANDEX user:key' },
  { id: 'naverClientId', label: 'NAVER CLIENT ID' },
  { id: 'naverClientSecret', label: 'NAVER SECRET' },
  { id: 'metager', label: 'METAGER KEY' },
  { id: 'swisscows', label: 'SWISSCOWS KEY' },
  { id: 'listennotes', label: 'LISTENNOTES KEY' },
  { id: 'searxngUrl', label: 'SEARXNG INSTANCE URL' },
];

export const STANDALONE_OPEN_FETCHERS = [
  'wikipedia', 'wikidata', 'github-users', 'github-repos', 'hackernews', 'stackoverflow',
  'archive.org', 'openlibrary', 'pubmed', 'duckduckgo', 'npm', 'openalex',
  'semantic-scholar', 'crossref', 'orcid', 'wayback', 'arxiv', 'core', 'europeana',
  'nominatim', 'doaj', 'wikibooks', 'commons', 'google-books', 'google-scholar',
  'gitlab-users', 'codeberg-users', 'mastodon', 'keybase', 'gravatar', 'reddit-users',
  'lichess', 'marginalia', 'wiby',
];

export const STANDALONE_KEY_BACKED_FETCHERS = [
  'brave', 'google', 'serpapi', 'shodan', 'hunter', 'intelx',
  'exa', 'mojeek', 'hibp', 'greynoise', 'searxng',
];

export const STANDALONE_SOURCE_TIERS = {
  wikipedia: 'open',
  wikidata: 'open',
  github: 'open',
  hackernews: 'open',
  stackoverflow: 'open',
  'archive.org': 'open',
  openlibrary: 'open',
  pubmed: 'open',
  npm: 'open',
  arxiv: 'open',
  core: 'open',
  europeana: 'open',
  nominatim: 'open',
  doaj: 'open',
  wikibooks: 'open',
  commons: 'open',
  'google-books': 'open',
  'google-scholar': 'open',
  gitlab: 'social',
  codeberg: 'social',
  mastodon: 'social',
  keybase: 'social',
  gravatar: 'social',
  'reddit-users': 'social',
  reddit: 'social',
  lichess: 'social',
  marginalia: 'open',
  wiby: 'open',
  wayback: 'wayback',
};

export const SERVER_CONNECTORS = [
  // ── CORE ──────────────────────────────────────────────────────────────────
  { id: 'brave', label: 'Brave Search', tier: 'core', requiresKey: 'brave', modulePath: './brave.js' },
  { id: 'serpapi', label: 'SerpAPI', tier: 'core', requiresKey: 'serpapi', modulePath: './serpapi.js' },
  { id: 'mojeek', label: 'Mojeek', tier: 'core', requiresKey: 'mojeek', modulePath: './mojeek.js' },
  { id: 'kagi', label: 'Kagi', tier: 'core', requiresKey: 'kagi', modulePath: './kagi.js' },
  { id: 'bing', label: 'Bing', tier: 'core', requiresKey: 'bing', modulePath: './bing.js' },
  { id: 'google', label: 'Google Custom Search', tier: 'core', requiresKey: ['google', 'googleCx'], modulePath: './google.js' },
  { id: 'metager', label: 'MetaGer', tier: 'core', requiresKey: 'metager', modulePath: './metager.js' },
  { id: 'swisscows', label: 'Swisscows', tier: 'core', requiresKey: 'swisscows', modulePath: './swisscows.js' },
  { id: 'listennotes', label: 'Listen Notes', tier: 'core', requiresKey: 'listennotes', modulePath: './listennotes.js' },
  { id: 'exa', label: 'Exa AI', tier: 'core', requiresKey: 'exa', modulePath: './exa.js' },
  { id: 'perplexity', label: 'Perplexity AI', tier: 'core', requiresKey: 'perplexity', modulePath: './perplexity.js' },

  // ── OPEN ──────────────────────────────────────────────────────────────────
  { id: 'duckduckgo', label: 'DuckDuckGo', tier: 'open', requiresKey: null, modulePath: './duckduckgo.js' },
  { id: 'searxng', label: 'SearXNG', tier: 'open', requiresKey: null, modulePath: './searxng.js' },
  { id: 'marginalia', label: 'Marginalia', tier: 'open', requiresKey: null, modulePath: './marginalia.js' },
  { id: 'wiby', label: 'Wiby', tier: 'open', requiresKey: null, modulePath: './wiby.js' },
  { id: 'qwant', label: 'Qwant', tier: 'open', requiresKey: null, modulePath: './qwant.js' },
  { id: 'yep', label: 'Yep', tier: 'open', requiresKey: null, modulePath: './yep.js' },
  { id: 'searchcode', label: 'SearchCode', tier: 'open', requiresKey: null, modulePath: './searchcode.js' },
  { id: 'grep.app', label: 'grep.app', tier: 'open', requiresKey: null, modulePath: './grepdotapp.js' },
  { id: 'openverse', label: 'Openverse', tier: 'open', requiresKey: null, modulePath: './openverse.js' },
  { id: 'base', label: 'BASE', tier: 'open', requiresKey: null, modulePath: './base.js' },
  { id: 'crt.sh', label: 'crt.sh', tier: 'open', requiresKey: null, modulePath: './crtsh.js' },
  { id: 'urlscan', label: 'urlscan.io', tier: 'open', requiresKey: null, modulePath: './urlscan.js' },
  { id: 'opencorporates', label: 'OpenCorporates', tier: 'open', requiresKey: null, modulePath: './opencorporates.js' },
  { id: 'opensanctions', label: 'OpenSanctions', tier: 'open', requiresKey: null, modulePath: './opensanctions.js' },
  { id: 'semantic-scholar', label: 'Semantic Scholar', tier: 'open', requiresKey: null, modulePath: './semanticscholar.js' },
  { id: 'crossref', label: 'CrossRef', tier: 'open', requiresKey: null, modulePath: './crossref.js' },
  { id: 'openalex', label: 'OpenAlex', tier: 'open', requiresKey: null, modulePath: './openalex.js' },
  { id: 'worldcat', label: 'WorldCat', tier: 'open', requiresKey: null, modulePath: './worldcat.js' },
  { id: 'ahmia', label: 'Ahmia', tier: 'open', requiresKey: null, modulePath: './ahmia.js' },
  { id: 'carrot2', label: 'Carrot2', tier: 'open', requiresKey: null, modulePath: './carrot2.js' },
  { id: 'whats-my-name', label: "What's My Name", tier: 'open', requiresKey: null, modulePath: './whatsMyName.js' },
  { id: 'social-searcher', label: 'Social Searcher', tier: 'open', requiresKey: null, modulePath: './socialsearcher.js' },
  { id: 'social-profiles', label: 'Social Profile Checker', tier: 'open', requiresKey: null, modulePath: './socialProfiles.js' },
  { id: 'arxiv', label: 'ArXiv', tier: 'open', requiresKey: null, modulePath: './arxiv.js' },
  { id: 'lens', label: 'Lens.org', tier: 'open', requiresKey: null, modulePath: './lens.js' },
  { id: 'orcid', label: 'ORCID', tier: 'open', requiresKey: null, modulePath: './orcid.js' },
  { id: 'stract', label: 'Stract', tier: 'open', requiresKey: null, modulePath: './stract.js' },
  { id: 'crowdview', label: 'CrowdView', tier: 'open', requiresKey: null, modulePath: './crowdview.js' },
  { id: 'yacy', label: 'YaCy', tier: 'open', requiresKey: null, modulePath: './yacy.js' },
  { id: 'europeana', label: 'Europeana', tier: 'open', requiresKey: null, modulePath: './europeana.js' },
  { id: 'jstor', label: 'JSTOR', tier: 'open', requiresKey: null, modulePath: './jstor.js' },
  { id: 'companies-house', label: 'UK Companies House', tier: 'open', requiresKey: null, modulePath: './companieshouse.js' },
  { id: 'google-maps', label: 'Google Maps', tier: 'open', requiresKey: null, modulePath: './googleMaps.js' },
  { id: 'google-books', label: 'Google Books', tier: 'open', requiresKey: null, modulePath: './googleBooks.js' },
  { id: 'bing-maps', label: 'Bing Maps', tier: 'open', requiresKey: null, modulePath: './bingMaps.js' },
  { id: 'yandex-maps', label: 'Yandex Maps', tier: 'open', requiresKey: null, modulePath: './yandexMaps.js' },
  { id: 'baidu-index', label: 'Baidu Index', tier: 'open', requiresKey: null, modulePath: './baiduIndex.js' },
  { id: 'weixin-sogou', label: 'Weixin Sogou', tier: 'open', requiresKey: null, modulePath: './weixinSogou.js' },
  { id: 'tusksearch', label: 'TuskSearch', tier: 'open', requiresKey: null, modulePath: './tuskSearch.js' },
  { id: 'excite', label: 'Excite', tier: 'open', requiresKey: null, modulePath: './excite.js' },
  { id: 'biznar', label: 'Biznar', tier: 'open', requiresKey: null, modulePath: './biznar.js' },
  { id: 'mednar', label: 'MedNar', tier: 'open', requiresKey: null, modulePath: './mednar.js' },
  { id: 'scienceresearch', label: 'ScienceResearch', tier: 'open', requiresKey: null, modulePath: './scienceResearch.js' },
  { id: 'kiddle', label: 'Kiddle', tier: 'open', requiresKey: null, modulePath: './kiddle.js' },
  { id: 'petalsearch', label: 'Petal Search', tier: 'open', requiresKey: null, modulePath: './petalSearch.js' },
  { id: 'grok', label: 'Grok', tier: 'open', requiresKey: null, modulePath: './grok.js' },
  { id: 'loc-gov', label: 'Library of Congress', tier: 'open', requiresKey: null, modulePath: './locGov.js' },
  { id: 'hathitrust', label: 'HathiTrust', tier: 'open', requiresKey: null, modulePath: './hathiTrust.js' },
  { id: 'british-museum', label: 'British Museum', tier: 'open', requiresKey: null, modulePath: './britishMuseum.js' },
  { id: 'royal-collection', label: 'Royal Collection Trust', tier: 'open', requiresKey: null, modulePath: './royalCollectionTrust.js' },
  { id: 'british-library', label: 'British Library', tier: 'open', requiresKey: null, modulePath: './britishLibrary.js' },

  // ── OSINT ─────────────────────────────────────────────────────────────────
  { id: 'shodan', label: 'Shodan', tier: 'osint', requiresKey: 'shodan', modulePath: './shodan.js' },
  { id: 'censys', label: 'Censys', tier: 'osint', requiresKey: ['censysId', 'censysSecret'], modulePath: './censys.js' },
  { id: 'hunter', label: 'Hunter.io', tier: 'osint', requiresKey: 'hunter', modulePath: './hunter.js' },
  { id: 'intelx', label: 'IntelX', tier: 'osint', requiresKey: 'intelx', modulePath: './intelx.js' },
  { id: 'publicwww', label: 'PublicWWW', tier: 'osint', requiresKey: 'publicwww', modulePath: './publicwww.js' },
  { id: 'tineye', label: 'TinEye', tier: 'osint', requiresKey: 'tineye', modulePath: './tineye.js' },
  { id: 'dehashed', label: 'DeHashed', tier: 'osint', requiresKey: 'dehashed', modulePath: './dehashed.js' },
  { id: 'haveibeenpwned', label: 'Have I Been Pwned', tier: 'osint', requiresKey: 'hibp', modulePath: './haveibeenpwned.js' },
  { id: 'greynoise', label: 'GreyNoise', tier: 'osint', requiresKey: 'greynoise', modulePath: './greynoise.js' },
  { id: 'pimeyes', label: 'PimEyes', tier: 'osint', requiresKey: null, modulePath: './pimeyes.js' },
  { id: 'libraries-io', label: 'Libraries.io', tier: 'osint', requiresKey: null, modulePath: './librariesIo.js' },
  { id: 'wolfram-alpha', label: 'Wolfram Alpha', tier: 'osint', requiresKey: null, modulePath: './wolframAlpha.js' },
  { id: 'netlas', label: 'Netlas', tier: 'osint', requiresKey: null, modulePath: './netlas.js' },

  // ── REGIONAL ──────────────────────────────────────────────────────────────
  { id: 'yandex', label: 'Yandex', tier: 'regional', requiresKey: 'yandex', modulePath: './yandex.js' },
  { id: 'baidu', label: 'Baidu', tier: 'regional', requiresKey: null, modulePath: './baidu.js' },
  { id: 'naver', label: 'Naver', tier: 'regional', requiresKey: ['naverClientId', 'naverClientSecret'], modulePath: './naver.js' },
  { id: 'sogou', label: 'Sogou', tier: 'regional', requiresKey: null, modulePath: './sogou.js' },
  { id: 'so360', label: 'So.com (360)', tier: 'regional', requiresKey: null, modulePath: './so360.js' },
  { id: 'seznam', label: 'Seznam', tier: 'regional', requiresKey: null, modulePath: './seznam.js' },
  { id: 'mail.ru', label: 'Mail.ru', tier: 'regional', requiresKey: null, modulePath: './mailru.js' },
  { id: 'rambler', label: 'Rambler', tier: 'regional', requiresKey: null, modulePath: './rambler.js' },

  // ── REGIONAL – Norway ──────────────────────────────────────────────────────
  { id: 'no-1881', label: '1881.no', tier: 'regional', requiresKey: null, modulePath: './no1881.js' },
  { id: 'gulesider', label: 'Gule Sider', tier: 'regional', requiresKey: null, modulePath: './gulesider.js' },
  { id: 'kvasir', label: 'Kvasir', tier: 'regional', requiresKey: null, modulePath: './kvasir.js' },
  { id: 'sol-no', label: 'Sol.no', tier: 'regional', requiresKey: null, modulePath: './solNo.js' },
  { id: 'brreg', label: 'Brønnøysundregistrene', tier: 'regional', requiresKey: null, modulePath: './brreg.js' },
  { id: 'proff-no', label: 'Proff.no', tier: 'regional', requiresKey: null, modulePath: './proffNo.js' },
  { id: 'norge-no', label: 'Norge.no', tier: 'regional', requiresKey: null, modulePath: './norgeNo.js' },
  { id: 'oria-no', label: 'Oria', tier: 'regional', requiresKey: null, modulePath: './oriaNO.js' },
  { id: 'digitalarkivet', label: 'Digitalarkivet', tier: 'regional', requiresKey: null, modulePath: './digitalarkivet.js' },

  // ── REGIONAL – Northern Ireland ────────────────────────────────────────────
  { id: 'nidirect', label: 'NIDirect', tier: 'regional', requiresKey: null, modulePath: './nidirect.js' },
  { id: 'proni-street', label: 'PRONI Street Directories', tier: 'regional', requiresKey: null, modulePath: './proniStreetDir.js' },
  { id: 'nibusinessinfo', label: 'NI Business Info', tier: 'regional', requiresKey: null, modulePath: './nibusinessinfo.js' },
  { id: 'nifed', label: 'NIFED', tier: 'regional', requiresKey: null, modulePath: './nifed.js' },
  { id: 'linkupni', label: 'LinkUpNI', tier: 'regional', requiresKey: null, modulePath: './linkupni.js' },
  { id: 'nijobs', label: 'NIJobs', tier: 'regional', requiresKey: null, modulePath: './nijobs.js' },
  { id: 'propertypal', label: 'PropertyPal', tier: 'regional', requiresKey: null, modulePath: './propertypal.js' },
  { id: 'propertynews', label: 'PropertyNews', tier: 'regional', requiresKey: null, modulePath: './propertynews.js' },
  { id: '4ni', label: '4NI', tier: 'regional', requiresKey: null, modulePath: './fourni.js' },
  { id: 'callupcontact', label: 'CallUpContact NI', tier: 'regional', requiresKey: null, modulePath: './callupcontact.js' },
  { id: 'belfasttelegraph', label: 'Belfast Telegraph', tier: 'regional', requiresKey: null, modulePath: './belfasttelegraph.js' },
  { id: 'irishnews', label: 'Irish News', tier: 'regional', requiresKey: null, modulePath: './irishnewsCo.js' },
  { id: 'sluggerotoole', label: "Slugger O'Toole", tier: 'regional', requiresKey: null, modulePath: './sluggerotoole.js' },
  { id: 'genesreunited', label: 'Genes Reunited', tier: 'regional', requiresKey: null, modulePath: './genesreunited.js' },
  { id: 'thegazette', label: 'The Gazette', tier: 'regional', requiresKey: null, modulePath: './thegazette.js' },

  // ── REGIONAL – Netherlands ─────────────────────────────────────────────────
  { id: 'kvk', label: 'KVK (Dutch Chamber)', tier: 'regional', requiresKey: null, modulePath: './kvk.js' },
  { id: 'business-gov-nl', label: 'Business.gov.nl', tier: 'regional', requiresKey: null, modulePath: './businessGovNl.js' },
  { id: 'telefoonboek', label: 'Telefoonboek', tier: 'regional', requiresKey: null, modulePath: './telefoonboek.js' },
  { id: 'detelefoongids', label: 'De Telefoongids', tier: 'regional', requiresKey: null, modulePath: './detelefoongids.js' },
  { id: 'goudengids', label: 'Gouden Gids', tier: 'regional', requiresKey: null, modulePath: './goudengids.js' },
  { id: 'telefoongids-nl', label: 'Telefoongids-NL', tier: 'regional', requiresKey: null, modulePath: './telefoongidsNl.js' },
  { id: 'kompass-nl', label: 'Kompass NL', tier: 'regional', requiresKey: null, modulePath: './kompassNl.js' },
  { id: 'dutchregistry', label: 'Dutch Registry', tier: 'regional', requiresKey: null, modulePath: './dutchregistry.js' },
  { id: 'adhocdata', label: 'Ad Hoc Data', tier: 'regional', requiresKey: null, modulePath: './adhocdata.js' },
  { id: 'kadaster', label: 'Kadaster', tier: 'regional', requiresKey: null, modulePath: './kadaster.js' },
  { id: 'archieven-nl', label: 'Archieven.nl', tier: 'regional', requiresKey: null, modulePath: './archievenNl.js' },
  { id: 'openarchieven', label: 'Open Archieven', tier: 'regional', requiresKey: null, modulePath: './openarchieven.js' },
  { id: 'wiewaswie', label: 'WieWasWie', tier: 'regional', requiresKey: null, modulePath: './wiewaswie.js' },
  { id: 'genealogie-online', label: 'Genealogie Online', tier: 'regional', requiresKey: null, modulePath: './genealogieOnline.js' },
  { id: 'delpher', label: 'Delpher', tier: 'regional', requiresKey: null, modulePath: './delpher.js' },
  { id: 'nieuwe-instituut', label: 'Het Nieuwe Instituut', tier: 'regional', requiresKey: null, modulePath: './nieuweInstituut.js' },
  { id: 'open-overheid', label: 'Open Overheid', tier: 'regional', requiresKey: null, modulePath: './openOverheid.js' },
  { id: 'rijksoverheid', label: 'Rijksoverheid', tier: 'regional', requiresKey: null, modulePath: './rijksoverheid.js' },
  { id: 'werk-nl', label: 'Werk.nl', tier: 'regional', requiresKey: null, modulePath: './werkNl.js' },
  { id: 'nationalevacaturebank', label: 'Nationale Vacaturebank', tier: 'regional', requiresKey: null, modulePath: './nationalevacaturebank.js' },
  { id: 'zoeken-nl', label: 'Zoeken.nl', tier: 'regional', requiresKey: null, modulePath: './zoekenNl.js' },

  // ── REGIONAL – Wales ───────────────────────────────────────────────────────
  { id: 'gov-wales', label: 'Gov.Wales', tier: 'regional', requiresKey: null, modulePath: './govWales.js' },
  { id: 'business-wales', label: 'Business Wales', tier: 'regional', requiresKey: null, modulePath: './businessWales.js' },
  { id: 'library-wales', label: 'National Library of Wales', tier: 'regional', requiresKey: null, modulePath: './libraryWales.js' },
  { id: 'archives-wales', label: 'Archives Wales', tier: 'regional', requiresKey: null, modulePath: './archivesWales.js' },
  { id: 'rcahmw', label: 'RCAHMW Coflein', tier: 'regional', requiresKey: null, modulePath: './rcahmw.js' },
  { id: 'cadw', label: 'Cadw', tier: 'regional', requiresKey: null, modulePath: './cadw.js' },
  { id: 'walesonline-dir', label: 'WalesOnline Directory', tier: 'regional', requiresKey: null, modulePath: './walesOnlineDir.js' },
  { id: 'findwales', label: 'FindWales', tier: 'regional', requiresKey: null, modulePath: './findWales.js' },
  { id: 'wales-business-network', label: 'Wales Business Network', tier: 'regional', requiresKey: null, modulePath: './walesBusinessNetwork.js' },
  { id: 'libraries-wales', label: 'Libraries Wales', tier: 'regional', requiresKey: null, modulePath: './librariesWales.js' },
  { id: 'national-archives-uk', label: 'UK National Archives', tier: 'regional', requiresKey: null, modulePath: './nationalArchivesUk.js' },
  { id: 'senedd', label: 'Senedd Wales', tier: 'regional', requiresKey: null, modulePath: './senedd.js' },

  // ── REGIONAL – London Historical ───────────────────────────────────────────
  { id: 'old-bailey', label: 'Old Bailey Online', tier: 'regional', requiresKey: null, modulePath: './oldBailey.js' },
  { id: 'layers-of-london', label: 'Layers of London', tier: 'regional', requiresKey: null, modulePath: './layersOfLondon.js' },
  { id: 'booth-poverty-map', label: 'Booth Poverty Map', tier: 'regional', requiresKey: null, modulePath: './boothPovertyMap.js' },
  { id: 'locating-london', label: 'Locating London', tier: 'regional', requiresKey: null, modulePath: './locatingLondon.js' },
  { id: 'london-picture-archive', label: 'London Picture Archive', tier: 'regional', requiresKey: null, modulePath: './londonPictureArchive.js' },
  { id: 'british-history-online', label: 'British History Online', tier: 'regional', requiresKey: null, modulePath: './britishHistoryOnline.js' },
  { id: 'map-of-london', label: 'Map of Early Modern London', tier: 'regional', requiresKey: null, modulePath: './mapOfLondon.js' },
  { id: 'gm-lives', label: 'GM Lives', tier: 'regional', requiresKey: null, modulePath: './gmLives.js' },

  // ── REGIONAL – Germany ─────────────────────────────────────────────────────
  { id: 'fireball', label: 'Fireball', tier: 'regional', requiresKey: null, modulePath: './fireball.js' },
  { id: 'gelbeseiten', label: 'Gelbe Seiten', tier: 'regional', requiresKey: null, modulePath: './gelbeseiten.js' },
  { id: 'dastelefonbuch', label: 'Das Telefonbuch', tier: 'regional', requiresKey: null, modulePath: './dasTelefonbuch.js' },
  { id: 'dasoertliche', label: 'Das Örtliche', tier: 'regional', requiresKey: null, modulePath: './dasOertliche.js' },
  { id: 'de-11880', label: '11880.com', tier: 'regional', requiresKey: null, modulePath: './de11880.js' },
  { id: 'meinestadt', label: 'meinestadt.de', tier: 'regional', requiresKey: null, modulePath: './meinestadt.js' },
  { id: 'web-de', label: 'Web.de', tier: 'regional', requiresKey: null, modulePath: './webDe.js' },
  { id: 't-online', label: 'T-Online', tier: 'regional', requiresKey: null, modulePath: './tOnline.js' },
  { id: 'gesis', label: 'GESIS', tier: 'regional', requiresKey: null, modulePath: './gesis.js' },
  { id: 'bund-de', label: 'Bund.de', tier: 'regional', requiresKey: null, modulePath: './bundDe.js' },

  // ── REGIONAL – Ireland ─────────────────────────────────────────────────────
  { id: 'goldenpages-ie', label: 'Golden Pages IE', tier: 'regional', requiresKey: null, modulePath: './goldenpagesIe.js' },
  { id: 'businessworld-ie', label: 'Business World IE', tier: 'regional', requiresKey: null, modulePath: './businessWorldIe.js' },
  { id: 'solocheck', label: 'SoloCheck', tier: 'regional', requiresKey: null, modulePath: './solocheck.js' },
  { id: 'cro-ie', label: 'CRO Ireland', tier: 'regional', requiresKey: null, modulePath: './croIe.js' },
  { id: 'gov-ie', label: 'Gov.ie', tier: 'regional', requiresKey: null, modulePath: './govIe.js' },
  { id: 'data-gov-ie', label: 'Data.gov.ie', tier: 'regional', requiresKey: null, modulePath: './dataGovIe.js' },
  { id: 'cso-ie', label: 'CSO Ireland', tier: 'regional', requiresKey: null, modulePath: './cso.js' },
  { id: 'national-archives-ie', label: 'National Archives IE', tier: 'regional', requiresKey: null, modulePath: './nationalArchivesIe.js' },
  { id: 'nli-ie', label: 'National Library of Ireland', tier: 'regional', requiresKey: null, modulePath: './nli.js' },
  { id: 'askaboutireland', label: 'Ask About Ireland', tier: 'regional', requiresKey: null, modulePath: './askAboutIreland.js' },
  { id: 'rootsireland', label: 'Roots Ireland', tier: 'regional', requiresKey: null, modulePath: './rootsIreland.js' },
  { id: 'findmypast-ie', label: 'FindMyPast IE', tier: 'regional', requiresKey: null, modulePath: './findmypastIe.js' },
  { id: 'myhome-ie', label: 'MyHome.ie', tier: 'regional', requiresKey: null, modulePath: './myhomeIe.js' },
  { id: 'daft-ie', label: 'Daft.ie', tier: 'regional', requiresKey: null, modulePath: './daft.js' },
  { id: 'jobs-ie', label: 'Jobs.ie', tier: 'regional', requiresKey: null, modulePath: './jobsIe.js' },
  { id: 'irishjobs', label: 'IrishJobs', tier: 'regional', requiresKey: null, modulePath: './irishjobs.js' },
  { id: 'rip-ie', label: 'RIP.ie', tier: 'regional', requiresKey: null, modulePath: './ripIe.js' },

  // ── REGIONAL – Egypt ───────────────────────────────────────────────────────
  { id: 'yellowpages-eg', label: 'Yellow Pages Egypt', tier: 'regional', requiresKey: null, modulePath: './yellowpagesEg.js' },
  { id: 'dalil140', label: 'Dalil 140', tier: 'regional', requiresKey: null, modulePath: './dalil140.js' },
  { id: 'forasna', label: 'Forasna', tier: 'regional', requiresKey: null, modulePath: './forasna.js' },
  { id: 'wuzzuf', label: 'Wuzzuf', tier: 'regional', requiresKey: null, modulePath: './wuzzuf.js' },
  { id: 'aqarmap', label: 'Aqarmap', tier: 'regional', requiresKey: null, modulePath: './aqarmap.js' },
  { id: 'dubizzle-eg', label: 'Dubizzle Egypt', tier: 'regional', requiresKey: null, modulePath: './dubizzleEg.js' },
  { id: 'olx-eg', label: 'OLX Egypt', tier: 'regional', requiresKey: null, modulePath: './olxEg.js' },
  { id: 'egypt-business', label: 'Egypt Business', tier: 'regional', requiresKey: null, modulePath: './egyptBusiness.js' },
  { id: 'egyptian-industry', label: 'Egyptian Industry', tier: 'regional', requiresKey: null, modulePath: './egyptianIndustry.js' },
  { id: 'idsc-eg', label: 'IDSC Egypt', tier: 'regional', requiresKey: null, modulePath: './idscEg.js' },
  { id: 'invest-egypt', label: 'Invest in Egypt', tier: 'regional', requiresKey: null, modulePath: './investEgypt.js' },
  { id: 'capmas', label: 'CAPMAS Egypt', tier: 'regional', requiresKey: null, modulePath: './capmas.js' },
  { id: 'egx', label: 'Egyptian Exchange', tier: 'regional', requiresKey: null, modulePath: './egx.js' },

  // ── REGIONAL – Belgium ─────────────────────────────────────────────────────
  { id: 'whitepages-be', label: 'White Pages Belgium', tier: 'regional', requiresKey: null, modulePath: './whitepagesBe.js' },

  // ── REGIONAL – DRC (Congo) ──────────────────────────────────────────────
  { id: 'acp-cd', label: 'ACP Congo', tier: 'regional', requiresKey: null, modulePath: './acpCd.js' },
  { id: 'rcst-cd', label: 'RCST Congo', tier: 'regional', requiresKey: null, modulePath: './rcstCd.js' },
  { id: 'odd-dashboard-cd', label: 'ODD Dashboard Congo', tier: 'regional', requiresKey: null, modulePath: './oddDashboardCd.js' },
  { id: 'inrb-cd', label: 'INRB Congo', tier: 'regional', requiresKey: null, modulePath: './inrbCd.js' },
  { id: 'drc-precop-cd', label: 'DRC PreCOP Environment', tier: 'regional', requiresKey: null, modulePath: './drcPrecopCd.js' },
  { id: 'julisha-cd', label: 'Julisha Congo', tier: 'regional', requiresKey: null, modulePath: './julishaCd.js' },
  { id: 'pnmls-cd', label: 'PNMLS Documentation', tier: 'regional', requiresKey: null, modulePath: './pnmlsCd.js' },

  // ── REGIONAL – Argentina ────────────────────────────────────────────────────
  { id: 'infoleg-ar', label: 'InfoLeg Argentina', tier: 'regional', requiresKey: null, modulePath: './infolegAr.js' },
  { id: 'justicia-ar', label: 'Argentina Justicia', tier: 'regional', requiresKey: null, modulePath: './justiciaAr.js' },
  { id: 'mseg-ar', label: 'MSEG Buenos Aires', tier: 'regional', requiresKey: null, modulePath: './msegAr.js' },
  { id: 'pjn-ar', label: 'PJN Argentina', tier: 'regional', requiresKey: null, modulePath: './pjnAr.js' },
  { id: 'cij-ar', label: 'CIJ Argentina', tier: 'regional', requiresKey: null, modulePath: './cijAr.js' },
  { id: 'boletin-oficial-ar', label: 'Boletín Oficial Argentina', tier: 'regional', requiresKey: null, modulePath: './boletinOficialAr.js' },
  { id: 'afip-ar', label: 'AFIP Argentina', tier: 'regional', requiresKey: null, modulePath: './afipAr.js' },
  { id: 'datos-abiertos-ar', label: 'Datos Abiertos Argentina', tier: 'regional', requiresKey: null, modulePath: './datosAbiertosAr.js' },
  { id: 'migraciones-ar', label: 'Migraciones Argentina', tier: 'regional', requiresKey: null, modulePath: './migracionesAr.js' },
  { id: 'comprar-ar', label: 'Comprar Argentina', tier: 'regional', requiresKey: null, modulePath: './comprarAr.js' },

  // ── REGIONAL – Romania ──────────────────────────────────────────────────────
  { id: 'politia-ro', label: 'Romanian Police', tier: 'regional', requiresKey: null, modulePath: './politiaRo.js' },
  { id: 'politia-frontiera-ro', label: 'Border Police Romania', tier: 'regional', requiresKey: null, modulePath: './politiaFrontieraRo.js' },
  { id: 'onrc-ro', label: 'ONRC Romania', tier: 'regional', requiresKey: null, modulePath: './onrcRo.js' },
  { id: 'listafirme-ro', label: 'Lista Firme', tier: 'regional', requiresKey: null, modulePath: './listafirmeRo.js' },
  { id: 'romanian-companies', label: 'Romanian Companies', tier: 'regional', requiresKey: null, modulePath: './romanianCompanies.js' },
  { id: 'arhiva-nationala-ro', label: 'National Archives Romania', tier: 'regional', requiresKey: null, modulePath: './arhivaNationalaRo.js' },
  { id: 'biblioteca-nationala-ro', label: 'National Library Romania', tier: 'regional', requiresKey: null, modulePath: './bibliotecaNationalaRo.js' },
  { id: 'e-licitatie-ro', label: 'e-Licitatie Romania', tier: 'regional', requiresKey: null, modulePath: './eLicitatieRo.js' },
  { id: 'anaf-ro', label: 'ANAF Romania', tier: 'regional', requiresKey: null, modulePath: './anafRo.js' },
  { id: 'portal-just-ro', label: 'Portal Just Romania', tier: 'regional', requiresKey: null, modulePath: './portalJustRo.js' },
  { id: 'rejust-ro', label: 'ReJust Romania', tier: 'regional', requiresKey: null, modulePath: './rejustRo.js' },
  { id: 'rolii-ro', label: 'ROLII Romania', tier: 'regional', requiresKey: null, modulePath: './roliiRo.js' },
  { id: 'genealogica-ro', label: 'Genealogica Romania', tier: 'regional', requiresKey: null, modulePath: './genealogicaRo.js' },
  { id: 'sicap-ro', label: 'SICAP Romania', tier: 'regional', requiresKey: null, modulePath: './sicapRo.js' },

  // ── REGIONAL – Eritrea ──────────────────────────────────────────────────────
  { id: 'shabait-er', label: 'Shabait Eritrea', tier: 'regional', requiresKey: null, modulePath: './shabaitEr.js' },
  { id: 'eritrea-info-er', label: 'Eritrea Information', tier: 'regional', requiresKey: null, modulePath: './eritreaInfoEr.js' },
  { id: 'eritrea-yellow-pages', label: 'Eritrea Yellow Pages', tier: 'regional', requiresKey: null, modulePath: './eritreaYellowPages.js' },
  { id: 'erilaw-er', label: 'EriLaw', tier: 'regional', requiresKey: null, modulePath: './erilawEr.js' },
  { id: 'worldlii-er', label: 'WorldLII Eritrea', tier: 'regional', requiresKey: null, modulePath: './worldliiEr.js' },

  // ── REGIONAL – Iran ─────────────────────────────────────────────────────────
  { id: 'irandoc-ir', label: 'IranDoc', tier: 'regional', requiresKey: null, modulePath: './irandocIr.js' },
  { id: 'sid-ir', label: 'SID Iran', tier: 'regional', requiresKey: null, modulePath: './sidIr.js' },
  { id: 'nlai-ir', label: 'National Library Iran', tier: 'regional', requiresKey: null, modulePath: './nlaiIr.js' },
  { id: 'jref-ir', label: 'JREF Iran', tier: 'regional', requiresKey: null, modulePath: './jrefIr.js' },
  { id: 'vlist-ir', label: 'VList Iran', tier: 'regional', requiresKey: null, modulePath: './vlistIr.js' },
  { id: 'company-register-ir', label: 'Company Register Iran', tier: 'regional', requiresKey: null, modulePath: './companyRegisterIr.js' },
  { id: 'symposia-ir', label: 'Symposia Iran', tier: 'regional', requiresKey: null, modulePath: './symposiaIr.js' },
  { id: 'trade-with-iran', label: 'Trade With Iran', tier: 'regional', requiresKey: null, modulePath: './tradeWithIranIr.js' },
  { id: 'mfa-ir', label: 'MFA Iran', tier: 'regional', requiresKey: null, modulePath: './mfaIr.js' },
  { id: 'iran-law-ir', label: 'Iran Law Journal', tier: 'regional', requiresKey: null, modulePath: './iranLawIr.js' },

  // ── REGIONAL – Luxembourg ───────────────────────────────────────────────────
  { id: 'lbr-lu', label: 'LBR Luxembourg', tier: 'regional', requiresKey: null, modulePath: './lbrLu.js' },
  { id: 'guichet-lu', label: 'Guichet Luxembourg', tier: 'regional', requiresKey: null, modulePath: './guichetLu.js' },
  { id: 'legilux-lu', label: 'Legilux', tier: 'regional', requiresKey: null, modulePath: './legiluxLu.js' },
  { id: 'justice-lu', label: 'Justice Luxembourg', tier: 'regional', requiresKey: null, modulePath: './justiceLu.js' },
  { id: 'data-lu', label: 'Data Luxembourg', tier: 'regional', requiresKey: null, modulePath: './dataLu.js' },
  { id: 'geoportail-lu', label: 'Geoportail Luxembourg', tier: 'regional', requiresKey: null, modulePath: './geoportailLu.js' },
  { id: 'police-lu', label: 'Police Luxembourg', tier: 'regional', requiresKey: null, modulePath: './policeLu.js' },
  { id: 'editus-lu', label: 'Editus Luxembourg', tier: 'regional', requiresKey: null, modulePath: './editusLu.js' },
  { id: 'proff-lu', label: 'Proff Luxembourg', tier: 'regional', requiresKey: null, modulePath: './proffLu.js' },
  { id: 'archives-lu', label: 'Archives Luxembourg', tier: 'regional', requiresKey: null, modulePath: './archivesLu.js' },
  { id: 'bnl-lu', label: 'National Library Luxembourg', tier: 'regional', requiresKey: null, modulePath: './bnlLu.js' },
  { id: 'cc-lu', label: 'Chamber of Commerce Luxembourg', tier: 'regional', requiresKey: null, modulePath: './ccLu.js' },

  // ── REGIONAL – London Boroughs ──────────────────────────────────────────────
  { id: 'harrow-planning', label: 'Harrow Planning', tier: 'regional', requiresKey: null, modulePath: './harrowPlanning.js' },
  { id: 'richmond-planning', label: 'Richmond Planning', tier: 'regional', requiresKey: null, modulePath: './richmondPlanning.js' },
  { id: 'wandsworth-planning', label: 'Wandsworth Planning', tier: 'regional', requiresKey: null, modulePath: './wandsworthPlanning.js' },
  { id: 'merton-planning', label: 'Merton Planning', tier: 'regional', requiresKey: null, modulePath: './mertonPlanning.js' },
  { id: 'bromley-planning', label: 'Bromley Planning', tier: 'regional', requiresKey: null, modulePath: './bromleyPlanning.js' },
  { id: 'sutton-planning', label: 'Sutton Planning', tier: 'regional', requiresKey: null, modulePath: './suttonPlanning.js' },
  { id: 'kingston-planning', label: 'Kingston Planning', tier: 'regional', requiresKey: null, modulePath: './kingstonPlanning.js' },
  { id: 'enfield-planning', label: 'Enfield Planning', tier: 'regional', requiresKey: null, modulePath: './enfieldPlanning.js' },
  { id: 'hackney-archives', label: 'Hackney Archives', tier: 'regional', requiresKey: null, modulePath: './hackneyArchives.js' },
  { id: 'london-archives', label: 'London Archives', tier: 'regional', requiresKey: null, modulePath: './londonArchives.js' },
  { id: 'met-police', label: 'Metropolitan Police', tier: 'regional', requiresKey: null, modulePath: './metPolice.js' },
  { id: 'gmp-police', label: 'Greater Manchester Police', tier: 'regional', requiresKey: null, modulePath: './gmpPolice.js' },

  // ── REGIONAL – Cornwall ─────────────────────────────────────────────────────
  { id: 'cornwall-gov', label: 'Cornwall Council', tier: 'regional', requiresKey: null, modulePath: './cornwallGov.js' },
  { id: 'devon-cornwall-police', label: 'Devon & Cornwall Police', tier: 'regional', requiresKey: null, modulePath: './devonCornwallPolice.js' },

  // ── REGIONAL – Isle of Man ──────────────────────────────────────────────────
  { id: 'gov-im', label: 'Isle of Man Gov', tier: 'regional', requiresKey: null, modulePath: './govIm.js' },
  { id: 'planning-im', label: 'Isle of Man Planning', tier: 'regional', requiresKey: null, modulePath: './planningIm.js' },

  // ── REGIONAL – Birmingham ───────────────────────────────────────────────────
  { id: 'birmingham-planning', label: 'Birmingham Planning', tier: 'regional', requiresKey: null, modulePath: './birminghamPlanning.js' },

  // ── REGIONAL – New York State ──────────────────────────────────────────────
  { id: 'dol-ny', label: 'NY DOL Contractor Registry', tier: 'regional', requiresKey: null, modulePath: './dolNy.js' },
  { id: 'nyscr-ny', label: 'NY State Contract Reporter', tier: 'regional', requiresKey: null, modulePath: './nyscrNy.js' },
  { id: 'dmv-ny', label: 'NY DMV', tier: 'regional', requiresKey: null, modulePath: './dmvNy.js' },
  { id: 'nysm-ny', label: 'NY State Museum', tier: 'regional', requiresKey: null, modulePath: './nysmNy.js' },

  // ── REGIONAL – France ──────────────────────────────────────────────────────
  { id: 'pagesjaunes-fr', label: 'PagesJaunes', tier: 'regional', requiresKey: null, modulePath: './pagesJaunesFr.js' },
  { id: '118712-fr', label: '118712', tier: 'regional', requiresKey: null, modulePath: './fr118712.js' },
  { id: '118000-fr', label: '118000', tier: 'regional', requiresKey: null, modulePath: './fr118000.js' },
  { id: 'orange-annuaire-fr', label: 'Orange Annuaire', tier: 'regional', requiresKey: null, modulePath: './orangeAnnuaireFr.js' },
  { id: 'societe-fr', label: 'Societe.com', tier: 'regional', requiresKey: null, modulePath: './societeFr.js' },
  { id: 'verif-fr', label: 'Verif.com', tier: 'regional', requiresKey: null, modulePath: './verifFr.js' },
  { id: 'infobel-fr', label: 'Infobel France', tier: 'regional', requiresKey: null, modulePath: './infobelFr.js' },
  { id: 'europages-fr', label: 'Europages France', tier: 'regional', requiresKey: null, modulePath: './europagesFr.js' },
  { id: 'kompass-fr', label: 'Kompass France', tier: 'regional', requiresKey: null, modulePath: './kompassFr.js' },
  { id: 'service-public-fr', label: 'Service-Public.fr', tier: 'regional', requiresKey: null, modulePath: './servicePublicFr.js' },
  { id: 'jdn-fr', label: 'Journal du Net', tier: 'regional', requiresKey: null, modulePath: './jdnFr.js' },
  { id: 'recherche-fr', label: 'Recherche.fr', tier: 'regional', requiresKey: null, modulePath: './rechercheFr.js' },
  { id: 'voila-fr', label: 'Voila.fr', tier: 'regional', requiresKey: null, modulePath: './voilaFr.js' },

  // ── REGIONAL – Poland ──────────────────────────────────────────────────────
  { id: 'onet-pl', label: 'Onet.pl', tier: 'regional', requiresKey: null, modulePath: './onetPl.js' },
  { id: 'wp-pl', label: 'Wirtualna Polska', tier: 'regional', requiresKey: null, modulePath: './wpPl.js' },
  { id: 'interia-pl', label: 'Interia.pl', tier: 'regional', requiresKey: null, modulePath: './interiaPl.js' },
  { id: 'gazeta-pl', label: 'Gazeta.pl', tier: 'regional', requiresKey: null, modulePath: './gazetaPl.js' },
  { id: 'whitepages-pl', label: 'WhitePages Poland', tier: 'regional', requiresKey: null, modulePath: './whitepagesPl.js' },
  { id: 'biznes-gov-pl', label: 'Biznes.gov.pl', tier: 'regional', requiresKey: null, modulePath: './biznesGovPl.js' },
  { id: 'ceidg-pl', label: 'CEIDG Poland', tier: 'regional', requiresKey: null, modulePath: './ceidgPl.js' },
  { id: 'regon-pl', label: 'REGON Poland', tier: 'regional', requiresKey: null, modulePath: './regonPl.js' },
  { id: 'krs-pl', label: 'KRS Poland', tier: 'regional', requiresKey: null, modulePath: './krsPl.js' },
  { id: 'knf-pl', label: 'KNF Poland', tier: 'regional', requiresKey: null, modulePath: './knfPl.js' },
  { id: 'uprp-pl', label: 'UPRP Poland', tier: 'regional', requiresKey: null, modulePath: './uprpPl.js' },
  { id: 'ppm-pl', label: 'PPM.edu.pl', tier: 'regional', requiresKey: null, modulePath: './ppmPl.js' },
  { id: 'pkt-pl', label: 'PKT.pl', tier: 'regional', requiresKey: null, modulePath: './pktPl.js' },
  { id: 'zumi-pl', label: 'Zumi.pl', tier: 'regional', requiresKey: null, modulePath: './zumiPl.js' },
  { id: 'o2-pl', label: 'O2.pl', tier: 'regional', requiresKey: null, modulePath: './o2Pl.js' },

  // ── REGIONAL – Switzerland ────────────────────────────────────────────────
  { id: 'search-ch', label: 'Search.ch', tier: 'regional', requiresKey: null, modulePath: './searchCh.js' },
  { id: 'local-ch', label: 'Local.ch', tier: 'regional', requiresKey: null, modulePath: './localCh.js' },
  { id: 'tiger-ch', label: 'Tiger.ch', tier: 'regional', requiresKey: null, modulePath: './tigerCh.js' },

  // ── REGIONAL – South Korea ────────────────────────────────────────────────
  { id: 'daum-kr', label: 'Daum', tier: 'regional', requiresKey: null, modulePath: './daumKr.js' },
  { id: 'kakao-map-kr', label: 'Kakao Map', tier: 'regional', requiresKey: null, modulePath: './kakaoMapKr.js' },
  { id: 'nate-kr', label: 'Nate', tier: 'regional', requiresKey: null, modulePath: './nateKr.js' },
  { id: 'zum-kr', label: 'Zum', tier: 'regional', requiresKey: null, modulePath: './zumKr.js' },
  { id: '11st-kr', label: '11st', tier: 'regional', requiresKey: null, modulePath: './kr11st.js' },
  { id: 'coupang-kr', label: 'Coupang', tier: 'regional', requiresKey: null, modulePath: './coupangKr.js' },
  { id: 'gmarket-kr', label: 'Gmarket', tier: 'regional', requiresKey: null, modulePath: './gmarketKr.js' },
  { id: 'auction-kr', label: 'Auction', tier: 'regional', requiresKey: null, modulePath: './auctionKr.js' },
  { id: 'jobkorea-kr', label: 'JobKorea', tier: 'regional', requiresKey: null, modulePath: './jobKoreaKr.js' },
  { id: 'saramin-kr', label: 'Saramin', tier: 'regional', requiresKey: null, modulePath: './saraminKr.js' },
  { id: '114-kr', label: '114.co.kr', tier: 'regional', requiresKey: null, modulePath: './kr114.js' },
  { id: 'koreatechdesk', label: 'Korea Tech Desk', tier: 'regional', requiresKey: null, modulePath: './koreaTechDesk.js' },

  // ── REGIONAL – Scotland ────────────────────────────────────────────────────
  { id: 'nrs-catalogue', label: 'NRS Online Catalogue', tier: 'regional', requiresKey: null, modulePath: './nrsCatalogue.js' },
  { id: 'scotlands-people', label: 'ScotlandsPeople', tier: 'regional', requiresKey: null, modulePath: './scotlandsPeople.js' },
  { id: 'trove-scot', label: 'Trove.scot', tier: 'regional', requiresKey: null, modulePath: './troveScot.js' },
  { id: 'canmore', label: 'Canmore', tier: 'regional', requiresKey: null, modulePath: './canmore.js' },
  { id: 'pastmap', label: 'PastMap', tier: 'regional', requiresKey: null, modulePath: './pastmap.js' },
  { id: 'nls-collections', label: 'NLS Collections', tier: 'regional', requiresKey: null, modulePath: './nlsCollections.js' },
  { id: 'nls-manuscripts', label: 'NLS Manuscripts', tier: 'regional', requiresKey: null, modulePath: './nlsManuscripts.js' },
  { id: 'nls-maps', label: 'NLS Maps', tier: 'regional', requiresKey: null, modulePath: './nlsMaps.js' },
  { id: 'electric-scotland', label: 'Electric Scotland', tier: 'regional', requiresKey: null, modulePath: './electricScotland.js' },
  { id: 'scottish-indexes', label: 'Scottish Indexes', tier: 'regional', requiresKey: null, modulePath: './scottishIndexes.js' },
  { id: 'directories-scot', label: 'Directories.scot', tier: 'regional', requiresKey: null, modulePath: './directoriesScot.js' },
  { id: 'opendata-scot', label: 'OpenData.scot', tier: 'regional', requiresKey: null, modulePath: './opendataScot.js' },
  { id: 'stirling-archives', label: 'Stirling Archives', tier: 'regional', requiresKey: null, modulePath: './stirlingArchives.js' },
  { id: 'mapgenie-uk', label: 'MapGenie UK', tier: 'regional', requiresKey: null, modulePath: './mapgenieUk.js' },

  // ── REGIONAL – Peru ────────────────────────────────────────────────────────
  { id: 'debida-diligencia-pe', label: 'Debida Diligencia Peru', tier: 'regional', requiresKey: null, modulePath: './debidaDiligenciaPe.js' },
  { id: 'pj-pe', label: 'Poder Judicial Peru', tier: 'regional', requiresKey: null, modulePath: './pjPe.js' },
  { id: 'sunarp-pe', label: 'SUNARP Peru', tier: 'regional', requiresKey: null, modulePath: './sunarpPe.js' },
  { id: 'osce-pe', label: 'OSCE Peru', tier: 'regional', requiresKey: null, modulePath: './oscePe.js' },
  { id: 'sunat-pe', label: 'SUNAT Peru', tier: 'regional', requiresKey: null, modulePath: './sunatPe.js' },
  { id: 'migraciones-pe', label: 'Migraciones Peru', tier: 'regional', requiresKey: null, modulePath: './migracionesPe.js' },
  { id: 'sbs-pe', label: 'SBS Peru', tier: 'regional', requiresKey: null, modulePath: './sbsPe.js' },
  { id: 'jne-pe', label: 'JNE Peru', tier: 'regional', requiresKey: null, modulePath: './jnePe.js' },

  // ── REGIONAL – Denmark ─────────────────────────────────────────────────────
  { id: 'politi-dk', label: 'Danish Police', tier: 'regional', requiresKey: null, modulePath: './politiDk.js' },
  { id: 'domstol-dk', label: 'Danish Courts', tier: 'regional', requiresKey: null, modulePath: './domstolDk.js' },
  { id: 'retsinformation-dk', label: 'Retsinformation', tier: 'regional', requiresKey: null, modulePath: './retsinformationDk.js' },
  { id: 'virk-dk', label: 'Virk.dk', tier: 'regional', requiresKey: null, modulePath: './virkDk.js' },
  { id: 'cvr-dk', label: 'CVR Denmark', tier: 'regional', requiresKey: null, modulePath: './cvrDk.js' },
  { id: 'tinglysning-dk', label: 'Tinglysning Denmark', tier: 'regional', requiresKey: null, modulePath: './tinglysningDk.js' },
  { id: 'skat-dk', label: 'Skat Denmark', tier: 'regional', requiresKey: null, modulePath: './skatDk.js' },
  { id: 'proff-dk', label: 'Proff.dk', tier: 'regional', requiresKey: null, modulePath: './proffDk.js' },
  { id: 'krak-dk', label: 'Krak.dk', tier: 'regional', requiresKey: null, modulePath: './krakDk.js' },
  { id: 'boligen-dk', label: 'Boligsiden Denmark', tier: 'regional', requiresKey: null, modulePath: './boligenDk.js' },

  // ── REGIONAL – Lithuania ───────────────────────────────────────────────────
  { id: 'police-lt', label: 'Lithuanian Police', tier: 'regional', requiresKey: null, modulePath: './policeLt.js' },
  { id: 'ird-lt', label: 'IRD Lithuania', tier: 'regional', requiresKey: null, modulePath: './irdLt.js' },
  { id: 'lkpb-lt', label: 'LKPB Lithuania', tier: 'regional', requiresKey: null, modulePath: './lkpbLt.js' },
  { id: 'teismai-lt', label: 'Lithuanian Courts', tier: 'regional', requiresKey: null, modulePath: './teismaiLt.js' },
  { id: 'e-teismas-lt', label: 'Lithuanian E-Court', tier: 'regional', requiresKey: null, modulePath: './eTeismasLt.js' },
  { id: 'liteko-lt', label: 'LITEKO Court Decisions', tier: 'regional', requiresKey: null, modulePath: './litekoLt.js' },
  { id: 'lrs-lt', label: 'Lithuanian Parliament', tier: 'regional', requiresKey: null, modulePath: './lrsLt.js' },
  { id: 'infolex-lt', label: 'Infolex Legal', tier: 'regional', requiresKey: null, modulePath: './infolexLt.js' },
  { id: 'rekvizitai-lt', label: 'Rekvizitai Company Search', tier: 'regional', requiresKey: null, modulePath: './rekvizitaiLt.js' },
  { id: 'registru-centras-lt', label: 'Centre of Registers Lithuania', tier: 'regional', requiresKey: null, modulePath: './registruCentrasLt.js' },
  { id: 'vmi-lt', label: 'Lithuanian Tax Inspectorate', tier: 'regional', requiresKey: null, modulePath: './vmiLt.js' },
  { id: 'cpo-lt', label: 'CPO Lithuania', tier: 'regional', requiresKey: null, modulePath: './cpoLt.js' },
  { id: 'cvpp-lt', label: 'CVPP Public Procurement', tier: 'regional', requiresKey: null, modulePath: './cvppLt.js' },
  { id: 'lb-lt', label: 'Bank of Lithuania', tier: 'regional', requiresKey: null, modulePath: './lbLt.js' },
  { id: 'fntt-lt', label: 'FNTT Lithuania', tier: 'regional', requiresKey: null, modulePath: './fnttLt.js' },
  { id: 'lrv-open-data-lt', label: 'Lithuanian Open Data', tier: 'regional', requiresKey: null, modulePath: './lrvOpenDataLt.js' },
  { id: 'muitine-lt', label: 'Lithuanian Customs', tier: 'regional', requiresKey: null, modulePath: './muitineLt.js' },
  { id: 'e-tar-lt', label: 'Lithuanian Legal Acts Register', tier: 'regional', requiresKey: null, modulePath: './eTarLt.js' },

  // ── REGIONAL – US (Arizona / Misc) ─────────────────────────────────────────
  { id: 'azdor-az', label: 'AZ Unclaimed Property', tier: 'regional', requiresKey: null, modulePath: './azdorAz.js' },
  { id: 'missing-money', label: 'MissingMoney', tier: 'regional', requiresKey: null, modulePath: './missingMoney.js' },
  { id: 'pima-inmate', label: 'Pima County Inmate Search', tier: 'regional', requiresKey: null, modulePath: './pimaInmate.js' },
  { id: 'phoenix-open-data', label: 'Phoenix Open Data', tier: 'regional', requiresKey: null, modulePath: './phoenixOpenData.js' },
  { id: 'phoenix-public-records', label: 'Phoenix Public Records', tier: 'regional', requiresKey: null, modulePath: './phoenixPublicRecords.js' },
  { id: 'az-geo', label: 'AZ Geospatial Data', tier: 'regional', requiresKey: null, modulePath: './azGeo.js' },
  { id: 'azdhs-gis', label: 'AZ Health Services GIS', tier: 'regional', requiresKey: null, modulePath: './azdhsGis.js' },
  { id: 'phoenix-chamber', label: 'Phoenix Chamber', tier: 'regional', requiresKey: null, modulePath: './phoenixChamber.js' },
  { id: 'chandler-chamber', label: 'Chandler Chamber', tier: 'regional', requiresKey: null, modulePath: './chandlerChamber.js' },
  { id: 'just-go-az', label: 'Just Go Arizona', tier: 'regional', requiresKey: null, modulePath: './justGoAz.js' },
  { id: 'visit-arizona', label: 'Visit Arizona', tier: 'regional', requiresKey: null, modulePath: './visitArizona.js' },
  { id: 'azsos-trade-names', label: 'AZ Secretary of State Trade Names', tier: 'regional', requiresKey: null, modulePath: './azsosTradeNames.js' },
  { id: 'azcc-business', label: 'AZ Corporation Commission', tier: 'regional', requiresKey: null, modulePath: './azccBusiness.js' },
  { id: 'az-league-jobs', label: 'AZ League Jobs', tier: 'regional', requiresKey: null, modulePath: './azLeagueJobs.js' },
  { id: 'phx-soul', label: 'PHXSoul Business Directory', tier: 'regional', requiresKey: null, modulePath: './phxSoul.js' },
  { id: 'az-job-connection', label: 'AZ Job Connection', tier: 'regional', requiresKey: null, modulePath: './azJobConnection.js' },
  { id: 'arizona-at-work', label: 'Arizona@Work', tier: 'regional', requiresKey: null, modulePath: './arizonaAtWork.js' },
  { id: 'des-az-jobs', label: 'AZ DES Employment', tier: 'regional', requiresKey: null, modulePath: './desAzJobs.js' },
  { id: 'az-corrections', label: 'AZ Corrections Inmate Search', tier: 'regional', requiresKey: null, modulePath: './azCorrections.js' },
  { id: 'azdps', label: 'AZ Dept of Public Safety', tier: 'regional', requiresKey: null, modulePath: './azdps.js' },
  { id: 'icrime-watch', label: 'iCrimeWatch AZ', tier: 'regional', requiresKey: null, modulePath: './iCrimeWatch.js' },
  { id: 'nsopw', label: 'National Sex Offender Registry', tier: 'regional', requiresKey: null, modulePath: './nsopw.js' },
  { id: 'az-archives-online', label: 'AZ Archives Online', tier: 'regional', requiresKey: null, modulePath: './azArchivesOnline.js' },
  { id: 'az-library', label: 'AZ State Library', tier: 'regional', requiresKey: null, modulePath: './azLibrary.js' },

  // ── REGIONAL – UK Academic / Archives ──────────────────────────────────────
  { id: 'uk-data-service', label: 'UK Data Service', tier: 'regional', requiresKey: null, modulePath: './ukDataService.js' },
  { id: 'paul-mellon-centre', label: 'Paul Mellon Centre', tier: 'regional', requiresKey: null, modulePath: './paulMellonCentre.js' },
  { id: 'british-newspaper-archive', label: 'British Newspaper Archive', tier: 'regional', requiresKey: null, modulePath: './britishNewspaperArchive.js' },
  { id: 'gazetteer-uk', label: 'Gazetteer UK', tier: 'regional', requiresKey: null, modulePath: './gazetteerUk.js' },
  { id: 'genuki', label: 'GENUKI', tier: 'regional', requiresKey: null, modulePath: './genuki.js' },
  { id: 'british-listed-buildings', label: 'British Listed Buildings', tier: 'regional', requiresKey: null, modulePath: './britishListedBuildings.js' },

  // ── REGIONAL – UK Local History ────────────────────────────────────────────
  { id: 'leigh-surrey-history', label: 'Leigh & District History', tier: 'regional', requiresKey: null, modulePath: './leighSurreyHistory.js' },
  { id: 'huncote-history', label: 'Huncote Parish History', tier: 'regional', requiresKey: null, modulePath: './huncoteHistory.js' },
  { id: 'appleby-magna-history', label: 'Appleby Magna History', tier: 'regional', requiresKey: null, modulePath: './applebyMagnaHistory.js' },
  { id: 'flitwick-history', label: 'History of Flitwick', tier: 'regional', requiresKey: null, modulePath: './flitwickHistory.js' },
  { id: 'bblhs', label: 'Beds & Bucks Local History Society', tier: 'regional', requiresKey: null, modulePath: './bblhs.js' },
  { id: 'cemetery-scribes', label: 'Cemetery Scribes', tier: 'regional', requiresKey: null, modulePath: './cemeteryScribes.js' },
  { id: 'community-archives', label: 'Community Archives', tier: 'regional', requiresKey: null, modulePath: './communityArchives.js' },
  { id: 'the-old-school', label: 'The Old School Archive', tier: 'regional', requiresKey: null, modulePath: './theOldSchool.js' },
  { id: 'local-history-links', label: 'Local History Links', tier: 'regional', requiresKey: null, modulePath: './localHistoryLinks.js' },
  { id: 'ukbmd-parish', label: 'UKBMD Parish Records', tier: 'regional', requiresKey: null, modulePath: './ukbmdParish.js' },
  { id: 'historic-england', label: 'Historic England', tier: 'regional', requiresKey: null, modulePath: './historicEngland.js' },
  { id: 'exploring-surreys-past', label: "Exploring Surrey's Past", tier: 'regional', requiresKey: null, modulePath: './exploringSurreysPast.js' },
  { id: 'old-maps-online', label: 'Old Maps Online', tier: 'regional', requiresKey: null, modulePath: './oldMapsOnline.js' },

  // ── REGIONAL – Bolivia ─────────────────────────────────────────────────────
  { id: 'fiva-bo', label: 'FIVA Bolivia Tax', tier: 'regional', requiresKey: null, modulePath: './fivaBo.js' },
  { id: 'siat-bo', label: 'SIAT Bolivia Tax Info', tier: 'regional', requiresKey: null, modulePath: './siatBo.js' },
  { id: 'senapi-bo', label: 'SENAPI Bolivia IP', tier: 'regional', requiresKey: null, modulePath: './senapiBo.js' },
  { id: 'autoridad-minera-bo', label: 'Bolivia Mining Authority', tier: 'regional', requiresKey: null, modulePath: './autoridadMineraBo.js' },
  { id: 'gaceta-santa-cruz-bo', label: 'Santa Cruz Official Gazette', tier: 'regional', requiresKey: null, modulePath: './gacetaSantaCruzBo.js' },
  { id: 'bcb-bo', label: 'Central Bank of Bolivia', tier: 'regional', requiresKey: null, modulePath: './bcbBo.js' },
  { id: 'sicoes-bo', label: 'SICOES Bolivia Procurement', tier: 'regional', requiresKey: null, modulePath: './sicoesBo.js' },

  // ── REGIONAL – Camden ──────────────────────────────────────────────────────
  { id: 'open-camden', label: 'Camden Open Data', tier: 'regional', requiresKey: null, modulePath: './openCamden.js' },

  // ── META ──────────────────────────────────────────────────────────────────
  { id: 'startpage', label: 'Startpage', tier: 'meta', requiresKey: null, modulePath: './startpage.js' },
  { id: 'dogpile', label: 'Dogpile', tier: 'meta', requiresKey: null, modulePath: './dogpile.js' },
  { id: 'metacrawler', label: 'MetaCrawler', tier: 'meta', requiresKey: null, modulePath: './metacrawler.js' },
  { id: 'etools', label: 'eTools', tier: 'meta', requiresKey: null, modulePath: './etools.js' },
  { id: 'ecosia', label: 'Ecosia', tier: 'meta', requiresKey: null, modulePath: './ecosia.js' },
  { id: 'presearch', label: 'Presearch', tier: 'meta', requiresKey: null, modulePath: './presearch.js' },
  { id: 'webcrawler', label: 'WebCrawler', tier: 'meta', requiresKey: null, modulePath: './webcrawler.js' },
  { id: 'faganfinder', label: 'FaganFinder', tier: 'meta', requiresKey: null, modulePath: './faganfinder.js' },
  { id: 'yahoo', label: 'Yahoo', tier: 'meta', requiresKey: null, modulePath: './yahoo.js' },
  { id: 'gibiru', label: 'Gibiru', tier: 'meta', requiresKey: null, modulePath: './gibiru.js' },
  { id: 'freespoke', label: 'Freespoke', tier: 'meta', requiresKey: null, modulePath: './freespoke.js' },
  { id: 'mamma', label: 'Mamma', tier: 'meta', requiresKey: null, modulePath: './mamma.js' },
  { id: 'you.com', label: 'You.com', tier: 'meta', requiresKey: null, modulePath: './youcom.js' },

  // ── OBSCURE ───────────────────────────────────────────────────────────────
  { id: 'refseek', label: 'RefSeek', tier: 'obscure', requiresKey: null, modulePath: './refseek.js' },
  { id: 'lycos', label: 'Lycos', tier: 'obscure', requiresKey: null, modulePath: './lycos.js' },
  { id: 'millionshort', label: 'MillionShort', tier: 'obscure', requiresKey: null, modulePath: './millionshort.js' },
  { id: 'boardreader', label: 'BoardReader', tier: 'obscure', requiresKey: null, modulePath: './boardreader.js' },
  { id: 'sourcegraph', label: 'Sourcegraph', tier: 'obscure', requiresKey: null, modulePath: './sourcegraph.js' },
  { id: 'scholar-google', label: 'Google Scholar', tier: 'obscure', requiresKey: null, modulePath: './scholarGoogle.js' },
  { id: 'yippy', label: 'Yippy', tier: 'obscure', requiresKey: null, modulePath: './yippy.js' },
  { id: 'exactseek', label: 'ExactSeek', tier: 'obscure', requiresKey: null, modulePath: './exactseek.js' },
  { id: 'alltheinternet', label: 'AllTheInternet', tier: 'obscure', requiresKey: null, modulePath: './alltheinternet.js' },
  { id: 'oscobo', label: 'Oscobo', tier: 'obscure', requiresKey: null, modulePath: './oscobo.js' },
  { id: 'searchencrypt', label: 'SearchEncrypt', tier: 'obscure', requiresKey: null, modulePath: './searchencrypt.js' },
  { id: 'info', label: 'Info.com', tier: 'obscure', requiresKey: null, modulePath: './info.js' },
  { id: 'searchalot', label: 'SearchAlot', tier: 'obscure', requiresKey: null, modulePath: './searchalot.js' },
  { id: 'anoox', label: 'Anoox', tier: 'obscure', requiresKey: null, modulePath: './anoox.js' },
  { id: 'secretsearch', label: 'Secret Search Engine Labs', tier: 'obscure', requiresKey: null, modulePath: './secretsearch.js' },
  { id: 'blog-search', label: 'Blog Search', tier: 'obscure', requiresKey: null, modulePath: './blogsearch.js' },
  { id: 'findsounds', label: 'FindSounds', tier: 'obscure', requiresKey: null, modulePath: './findsounds.js' },
  { id: 'rpmfind', label: 'RPMFind', tier: 'obscure', requiresKey: null, modulePath: './rpmfind.js' },
  { id: 'worldwidescience', label: 'WorldWideScience', tier: 'obscure', requiresKey: null, modulePath: './worldwidescience.js' },
  { id: 'scienceopen', label: 'ScienceOpen', tier: 'obscure', requiresKey: null, modulePath: './scienceopen.js' },
  { id: 'krugle', label: 'Krugle', tier: 'obscure', requiresKey: null, modulePath: './krugle.js' },
  { id: 'researchgate', label: 'ResearchGate', tier: 'obscure', requiresKey: null, modulePath: './researchgate.js' },
  { id: 'academia', label: 'Academia.edu', tier: 'obscure', requiresKey: null, modulePath: './academia.js' },
  { id: 'ssrn', label: 'SSRN', tier: 'obscure', requiresKey: null, modulePath: './ssrn.js' },
  { id: 'gigablast', label: 'Gigablast', tier: 'obscure', requiresKey: null, modulePath: './gigablast.js' },
  { id: 'webwiki', label: 'WebWiki', tier: 'obscure', requiresKey: null, modulePath: './webwiki.js' },
  { id: '2lingual', label: '2lingual', tier: 'obscure', requiresKey: null, modulePath: './twoLingual.js' },
  { id: 'aol', label: 'AOL Search', tier: 'obscure', requiresKey: null, modulePath: './aol.js' },
  { id: 'exalead', label: 'Exalead', tier: 'obscure', requiresKey: null, modulePath: './exalead.js' },
  { id: 'givewater', label: 'GiveWater', tier: 'obscure', requiresKey: null, modulePath: './givewater.js' },
  { id: 'gnod', label: 'Gnod', tier: 'obscure', requiresKey: null, modulePath: './gnod.js' },

];

export const SERVER_TIER_MAP = Object.fromEntries(
  SERVER_CONNECTORS.map(({ id, tier }) => [id, tier])
);

export const SOURCE_TIER_MAP = {
  ...SERVER_TIER_MAP,
  ...STANDALONE_SOURCE_TIERS,
};

export const ENGINE_METADATA = {
  keyDefs: KEY_DEFS,
  standalone: {
    openFetchers: STANDALONE_OPEN_FETCHERS,
    keyBackedFetchers: STANDALONE_KEY_BACKED_FETCHERS,
    sourceTierMap: STANDALONE_SOURCE_TIERS,
  },
  serverConnectors: SERVER_CONNECTORS.map(({
    id,
    label,
    tier,
    requiresKey,
  }) => ({
    id,
    label,
    tier,
    requiresKey,
  })),
  serverTierMap: SERVER_TIER_MAP,
  sourceTierMap: SOURCE_TIER_MAP,
};
